/*
The MIT License (MIT)

Copyright (c) 2022 Kathryn J Knight

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/
/**
 * Hold results for parse and validate a WikiTree biography
 */
export class BiographyResults {

   bioResults = {

      stats: {
         bioIsEmpty: false,
         bioHasCategories: false,
         bioIsMarkedUnsourced: false,
         bioIsUncertainExistance: false,
         bioIsUndated: false,
         totalBioLines: 0,
         inlineReferencesCount: 0,      // number of <ref>
         possibleSourcesLineCount: 0   // number of lines that might contain sources
      },
      style: {
         bioHasNonCategoryTestBeforeBiographyHeading: false,
         bioHasStyleIssues: false,
         hasEndlessComment: false,
         bioIsMissingBiographyHeading: false,
         bioHeadingWithNoLinesFollowing: false,
         bioHasMultipleBioHeadings: false,
         bioHasRefWithoutEnd: false,
         bioHasSpanWithoutEndingSpan: false,
         bioIsMissingSourcesHeading: false,
         sourcesHeadingHasExtraEqual: false,
         bioHasMultipleSourceHeadings: false,
         misplacedLineCount: 0,      // between Sources and <references /> 
         bioIsMissingReferencesTag: false,
         bioHasMultipleReferencesTags: false,
         bioHasRefAfterReferences: false,
         acknowledgementsHeadingHasExtraEqual: false,
         bioHasAcknowledgementsBeforeSources: false,
         bioIsAutoGenerated: false
      },
      sources: {
         sourcesFound: false,

         // Invalid sources that were found - each an array
         // might not need/want these, depends on reporting
         invalidSource: [],
         //invalidStandAloneSource: [],
         //invalidPartialSource: [],
         //invalidStartPartialSource: [],
         //invalidSpanTargetSource: [],
         validSource: [],
      }
   };

   constructor() {
   }

   getResults() {
     return this.bioResults;
   }
}
