import { isMainDomain } from "../../core/pageType";
import { registerFeature, OptionType } from "../../core/options/options_registry";

const myCustomStyle = {
  name: "Custom Style",
  id: "customStyle",
  description: "Choose your own font colors, including visited links, and the style of headings.",
  category: "Global/Style",
  defaultValue: false,
  creators: [{ name: "Ian Beacall", wikitreeid: "Beacall-6" }],
  contributors: [],
  pages: [isMainDomain],
  options: [
    {
      id: "general",
      type: OptionType.GROUP,
      label: "Global",
      options: [
        { id: "global_background-color", type: "color", label: "Background color", defaultValue: "#ffffff" },
        {
          id: "global_color",
          type: "color",
          label: "Font color",
          defaultValue: "#393a3c",
        },
        {
          id: "global_font-family",
          type: OptionType.SELECT,
          label: "Font family",
          values: [
            { value: "Arial, sans-serif", text: "Arial" },
            { value: "'Comic Sans MS', cursive", text: "Comic Sans MS" },
            { value: "'Courier New', monospace", text: "Courier New" },
            { value: "Georgia, serif", text: "Georgia" },
            { value: "'Lucida Console', monospace", text: "Lucida Console" },
            { value: "OpenDyslexic, 'Comic Sans MS'", text: "OpenDyslexic" },
            { value: "'Roboto', sans-serif", text: "Roboto" },
            { value: "Tahoma, sans-serif", text: "Tahoma" },
            { value: "'Times New Roman', serif", text: "Times New Roman" },
            { value: "'Trebuchet MS', sans-serif", text: "Trebuchet MS" },
            { value: "Verdana, sans-serif", text: "Verdana" },
          ],
          defaultValue: "'Roboto', sans-serif",
        },
        {
          id: "roundedCorners",
          type: OptionType.CHECKBOX,
          label: "Rounded corners",
          defaultValue: false,
        },
        {
          id: "editor_font-size",
          type: OptionType.SELECT,
          label: "Editor font size",
          values: [
            { value: "100", text: "100%" },
            { value: "110", text: "110%" },
            { value: "120", text: "120%" },
            { value: "130", text: "130%" },
            { value: "140", text: "140%" },
            { value: "150", text: "150%" },
            { value: "160", text: "160%" },
            { value: "170", text: "170%" },
            { value: "180", text: "180%" },
            { value: "190", text: "190%" },
            { value: "200", text: "200%" },
            { value: "210", text: "210%" },
            { value: "220", text: "220%" },
            { value: "230", text: "230%" },
            { value: "240", text: "240%" },
            { value: "250", text: "250%" },
          ],
          defaultValue: "100",
        },
      ],
    },
    {
      id: "headings",
      type: OptionType.GROUP,
      label: "Headings",
      options: [
        {
          id: "headings_background-color",
          type: "color",
          label: "Background color",
          defaultValue: "#ffffff",
        },
        {
          id: "headings_color",
          type: "color",
          label: "Text color",
          defaultValue: "#000000",
        },
        {
          id: "headings_padding",
          type: "number",
          label: "Padding",
          defaultValue: "0",
        },
        {
          id: "headings_border-radius",
          type: "number",
          label: "Border radius",
          defaultValue: "0",
        },
        {
          id: "headings_box-shadow",
          type: "number",
          label: "Shadow",
          defaultValue: "0",
        },
      ],
    },
    {
      id: "standardColors",
      type: OptionType.GROUP,
      label: "Profile Background Colors",
      options: [
        {
          id: "color1_background-color",
          type: "color",
          label: "Background color 1 (Header, footer, profile tabs, etc.)",
          defaultValue: "#f0f0eb",
        },
        {
          id: "color1_color",
          type: "color",
          label: "Color 1 (Header, profile tabs, etc.) text",
          defaultValue: "#25422D",
        },
        {
          id: "color2_background-color",
          type: "color",
          label: "Background color 2 (Active tab, buttons)",
          defaultValue: "#ffffff",
        },
        {
          id: "color2_color",
          type: "color",
          label: "Color 2 (Active tab, buttons) text",
          defaultValue: "#393a3c",
        },
        {
          id: "color3_background-color",
          type: "color",
          label: "Background color 3 (Profile manager)",
          defaultValue: "#F7F8F5",
        },
        {
          id: "color4_background-color",
          type: "color",
          label: "Background color 4 (Boxes: Collaboration, Research, etc.)",
          defaultValue: "#ffee99",
        },
      ],
    },
    {
      id: "linkColors",
      type: OptionType.GROUP,
      label: "Profile Link Colors",
      options: [
        {
          id: "link_color",
          type: "color",
          label: "Link color",
          defaultValue: "#008000",
        },
        {
          id: "visitedLink_color",
          type: "color",
          label: "Visited link color",
          defaultValue: "#800080",
        },
      ],
    },
    {
      id: "g2gColors",
      type: OptionType.GROUP,
      label: "G2G",
      options: [
        {
          id: "tag_color",
          type: "color",
          label: "Tag text color",
          defaultValue: "#25422d",
        },
        {
          id: "tag_background-color",
          type: "color",
          label: "Tag background color",
          defaultValue: "#e1f0b4",
        },
        {
          id: "tagHover_color",
          type: "color",
          label: "Tag hover text color",
          defaultValue: "#25422d",
        },
        {
          id: "tagHover_background-color",
          type: "color",
          label: "Tag hover background color",
          defaultValue: "#cbdd98",
        },
        {
          id: "voteCount_background-color",
          type: "color",
          label: "Vote count box background color",
          defaultValue: "#e1f0b4",
        },
        {
          id: "voteCount_color",
          type: "color",
          label: "Vote count box text color",
          defaultValue: "#25422d",
        },
        {
          id: "answerCount_background-color",
          type: "color",
          label: "Answer count box background color",
          defaultValue: "#ffee99",
        },
        {
          id: "answerCount_color",
          type: "color",
          label: "Answer count box text color",
          defaultValue: "#25422d",
        },
      ],
    },
  ],
};

registerFeature(myCustomStyle);
