/*
Created By: Ian Beacall (Beacall-6)

Place-name lookup tables used to decide whether two locations agree, conflict, or say
nothing about each other.

*/

export const UNKNOWN_TOKENS = new Set(["", "blank", "n a", "na", "none", "null", "unk", "unknown"]);

export const WEAK_LOCATION_TOKENS = new Set([
  "australia",
  "canada",
  "england",
  "ireland",
  "scotland",
  "united kingdom",
  "united states",
  "usa",
  "wales",
]);

export const MODERN_COUNTRY_NAMES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Costa Rica",
  "Cote d'Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Republic of the Congo",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const US_STATE_NAMES = new Set([
  "alabama",
  "alaska",
  "arizona",
  "arkansas",
  "california",
  "colorado",
  "connecticut",
  "delaware",
  "district of columbia",
  "florida",
  "georgia",
  "hawaii",
  "idaho",
  "illinois",
  "indiana",
  "iowa",
  "kansas",
  "kentucky",
  "louisiana",
  "maine",
  "maryland",
  "massachusetts",
  "michigan",
  "minnesota",
  "mississippi",
  "missouri",
  "montana",
  "nebraska",
  "nevada",
  "new hampshire",
  "new jersey",
  "new mexico",
  "new york",
  "north carolina",
  "north dakota",
  "ohio",
  "oklahoma",
  "oregon",
  "pennsylvania",
  "rhode island",
  "south carolina",
  "south dakota",
  "tennessee",
  "texas",
  "utah",
  "vermont",
  "virginia",
  "washington",
  "west virginia",
  "wisconsin",
  "wyoming",
]);

export const US_STATE_CODE_TO_NAME = {
  AL: "Alabama",
  AK: "Alaska",
  AZ: "Arizona",
  AR: "Arkansas",
  CA: "California",
  CO: "Colorado",
  CT: "Connecticut",
  DE: "Delaware",
  FL: "Florida",
  GA: "Georgia",
  HI: "Hawaii",
  ID: "Idaho",
  IL: "Illinois",
  IN: "Indiana",
  IA: "Iowa",
  KS: "Kansas",
  KY: "Kentucky",
  LA: "Louisiana",
  ME: "Maine",
  MD: "Maryland",
  MA: "Massachusetts",
  MI: "Michigan",
  MN: "Minnesota",
  MS: "Mississippi",
  MO: "Missouri",
  MT: "Montana",
  NE: "Nebraska",
  NV: "Nevada",
  NH: "New Hampshire",
  NJ: "New Jersey",
  NM: "New Mexico",
  NY: "New York",
  NC: "North Carolina",
  ND: "North Dakota",
  OH: "Ohio",
  OK: "Oklahoma",
  OR: "Oregon",
  PA: "Pennsylvania",
  RI: "Rhode Island",
  SC: "South Carolina",
  SD: "South Dakota",
  TN: "Tennessee",
  TX: "Texas",
  UT: "Utah",
  VT: "Vermont",
  VA: "Virginia",
  WA: "Washington",
  WV: "West Virginia",
  WI: "Wisconsin",
  WY: "Wyoming",
  DC: "District of Columbia",
};

export const AMBIGUOUS_COUNTRY_STATE_NAMES = new Set(["georgia"]);

export const US_COUNTRY_MARKERS = new Set(["u s", "u s a", "united states", "united states of america", "us", "usa"]);

export const US_STATE_ABBREVIATION_TO_NAME = {
  ala: "Alabama",
  ariz: "Arizona",
  ark: "Arkansas",
  calif: "California",
  colo: "Colorado",
  conn: "Connecticut",
  del: "Delaware",
  fla: "Florida",
  ill: "Illinois",
  ind: "Indiana",
  kans: "Kansas",
  mass: "Massachusetts",
  mich: "Michigan",
  minn: "Minnesota",
  miss: "Mississippi",
  mont: "Montana",
  neb: "Nebraska",
  nev: "Nevada",
  okla: "Oklahoma",
  ore: "Oregon",
  penn: "Pennsylvania",
  penna: "Pennsylvania",
  tenn: "Tennessee",
  tex: "Texas",
  wash: "Washington",
  wis: "Wisconsin",
  wisc: "Wisconsin",
  "w va": "West Virginia",
  wva: "West Virginia",
  wyo: "Wyoming",
};

export const CANADA_REGIONS = new Set([
  "acadia",
  "acadie",
  "alberta",
  "british columbia",
  "canada",
  "canada east",
  "canada west",
  "dominion of canada",
  "lower canada",
  "manitoba",
  "new brunswick",
  "new france",
  "newfoundland",
  "newfoundland and labrador",
  "nouvelle france",
  "nova scotia",
  "nunavut",
  "ontario",
  "prince edward island",
  "province of canada",
  "quebec",
  "saskatchewan",
  "upper canada",
  "yukon",
]);

export const CANADA_REGION_LABELS = {
  alberta: "Alberta",
  "british columbia": "British Columbia",
  manitoba: "Manitoba",
  "new brunswick": "New Brunswick",
  newfoundland: "Newfoundland and Labrador",
  "newfoundland and labrador": "Newfoundland and Labrador",
  "nova scotia": "Nova Scotia",
  nunavut: "Nunavut",
  ontario: "Ontario",
  "prince edward island": "Prince Edward Island",
  quebec: "Quebec",
  saskatchewan: "Saskatchewan",
  yukon: "Yukon",
  "new france": "Quebec",
  "nouvelle france": "Quebec",
  "lower canada": "Quebec",
  "upper canada": "Ontario",
  "canada east": "Quebec",
  "canada west": "Ontario",
  acadie: "Nova Scotia",
  acadia: "Nova Scotia",
};

export const AUSTRALIA_REGIONS = new Set([
  "australia",
  "australian capital territory",
  "colony of new south wales",
  "colony of queensland",
  "colony of south australia",
  "colony of tasmania",
  "colony of victoria",
  "colony of western australia",
  "new south wales",
  "northern territory",
  "queensland",
  "south australia",
  "tasmania",
  "van diemen s land",
  "van diemens land",
  "victoria",
  "western australia",
]);

export const AUSTRALIA_REGION_LABELS = {
  "new south wales": "New South Wales",
  queensland: "Queensland",
  "south australia": "South Australia",
  tasmania: "Tasmania",
  victoria: "Victoria",
  "western australia": "Western Australia",
  "northern territory": "Northern Territory",
  "australian capital territory": "Australian Capital Territory",
  "colony of new south wales": "New South Wales",
  "colony of queensland": "Queensland",
  "colony of south australia": "South Australia",
  "colony of tasmania": "Tasmania",
  "colony of victoria": "Victoria",
  "colony of western australia": "Western Australia",
  "van diemens land": "Tasmania",
  "van diemen s land": "Tasmania",
};

export const ENGLAND_COUNTY_LABELS = {
  bedfordshire: "Bedfordshire",
  berkshire: "Berkshire",
  buckinghamshire: "Buckinghamshire",
  cambridgeshire: "Cambridgeshire",
  cheshire: "Cheshire",
  cornwall: "Cornwall",
  cumberland: "Cumberland",
  derbyshire: "Derbyshire",
  devon: "Devon",
  dorset: "Dorset",
  durham: "Durham",
  essex: "Essex",
  gloucestershire: "Gloucestershire",
  hampshire: "Hampshire",
  herefordshire: "Herefordshire",
  hertfordshire: "Hertfordshire",
  huntingdonshire: "Huntingdonshire",
  kent: "Kent",
  lancashire: "Lancashire",
  leicestershire: "Leicestershire",
  lincolnshire: "Lincolnshire",
  middlesex: "Middlesex",
  norfolk: "Norfolk",
  northamptonshire: "Northamptonshire",
  northumberland: "Northumberland",
  nottinghamshire: "Nottinghamshire",
  oxfordshire: "Oxfordshire",
  rutland: "Rutland",
  shropshire: "Shropshire",
  somerset: "Somerset",
  staffordshire: "Staffordshire",
  suffolk: "Suffolk",
  surrey: "Surrey",
  sussex: "Sussex",
  warwickshire: "Warwickshire",
  westmorland: "Westmorland",
  wiltshire: "Wiltshire",
  worcestershire: "Worcestershire",
  yorkshire: "Yorkshire",
};

export const SCOTLAND_COUNTY_LABELS = {
  aberdeenshire: "Aberdeenshire",
  angus: "Angus",
  argyll: "Argyll",
  ayrshire: "Ayrshire",
  banffshire: "Banffshire",
  berwickshire: "Berwickshire",
  bute: "Bute",
  caithness: "Caithness",
  clackmannanshire: "Clackmannanshire",
  dumfriesshire: "Dumfriesshire",
  dunbartonshire: "Dunbartonshire",
  "east lothian": "East Lothian",
  fife: "Fife",
  "inverness shire": "Inverness-shire",
  kincardineshire: "Kincardineshire",
  "kinross shire": "Kinross-shire",
  kirkcudbrightshire: "Kirkcudbrightshire",
  lanarkshire: "Lanarkshire",
  midlothian: "Midlothian",
  morayshire: "Morayshire",
  nairnshire: "Nairnshire",
  orkney: "Orkney",
  peeblesshire: "Peeblesshire",
  perthshire: "Perthshire",
  renfrewshire: "Renfrewshire",
  "ross shire": "Ross-shire",
  roxburghshire: "Roxburghshire",
  selkirkshire: "Selkirkshire",
  shetland: "Shetland",
  stirlingshire: "Stirlingshire",
  sutherland: "Sutherland",
  "west lothian": "West Lothian",
  wigtownshire: "Wigtownshire",
};

export const WALES_COUNTY_LABELS = {
  anglesey: "Anglesey",
  brecknockshire: "Brecknockshire",
  caernarfonshire: "Caernarfonshire",
  cardiganshire: "Cardiganshire",
  carmarthenshire: "Carmarthenshire",
  denbighshire: "Denbighshire",
  flintshire: "Flintshire",
  glamorgan: "Glamorgan",
  merionethshire: "Merionethshire",
  monmouthshire: "Monmouthshire",
  montgomeryshire: "Montgomeryshire",
  pembrokeshire: "Pembrokeshire",
  radnorshire: "Radnorshire",
};

export const IRELAND_COUNTIES = new Set([
  "antrim",
  "armagh",
  "carlow",
  "cavan",
  "clare",
  "cork",
  "derry",
  "donegal",
  "down",
  "dublin",
  "fermanagh",
  "galway",
  "kerry",
  "kildare",
  "kilkenny",
  "laois",
  "leitrim",
  "limerick",
  "longford",
  "louth",
  "mayo",
  "meath",
  "monaghan",
  "offaly",
  "roscommon",
  "sligo",
  "tipperary",
  "tyrone",
  "waterford",
  "westmeath",
  "wexford",
  "wicklow",
]);

export const UK_REGIONS = new Set(["england", "great britain", "scotland", "united kingdom", "wales"]);

export const UK_REGION_LABELS = {
  england: "England",
  scotland: "Scotland",
  wales: "Wales",
  "northern ireland": "Northern Ireland",
};

export const US_TERRITORY_REGIONS = new Set([
  "american samoa",
  "commonwealth of puerto rico",
  "commonwealth of the northern mariana islands",
  "guam",
  "northern mariana islands",
  "puerto rico",
  "u s minor outlying islands",
  "u s virgin islands",
  "united states virgin islands",
  "us minor outlying islands",
  "us virgin islands",
  "virgin islands of the united states",
]);

export const SOUTH_AFRICA_REGIONS = new Set([
  "cape colony",
  "cape province",
  "natal colony",
  "orange free state",
  "orange river colony",
  "south africa",
  "south african republic",
  "transvaal",
  "zuid afrikaansche republek",
  "zuid afrikaansche republiek",
  "zuid afrikaansche republik",
  "zuid afrikaansche republyek",
]);

export const ALIASES = {
  usa: "United States",
  us: "United States",
  "u s a": "United States",
  "u s": "United States",
  "estados unidos": "United States",
  "etats unis": "United States",
  "vereinigte staaten": "United States",
  "united states of america": "United States",
  "united states": "United States",
  "american samoa": "United States",
  as: "United States",
  "commonwealth of puerto rico": "United States",
  "commonwealth of the northern mariana islands": "United States",
  guam: "United States",
  gu: "United States",
  "northern mariana islands": "United States",
  "puerto rico": "United States",
  pr: "United States",
  "u s virgin islands": "United States",
  "us virgin islands": "United States",
  "united states virgin islands": "United States",
  "virgin islands of the united states": "United States",
  vi: "United States",
  mp: "United States",
  "u s minor outlying islands": "United States",
  "us minor outlying islands": "United States",
  uk: "United Kingdom",
  "u k": "United Kingdom",
  "great britain": "United Kingdom",
  grossbritannien: "United Kingdom",
  "reino unido": "United Kingdom",
  "royaume uni": "United Kingdom",
  "united kingdom": "United Kingdom",
  england: "United Kingdom",
  scotland: "United Kingdom",
  wales: "United Kingdom",
  ireland: "Ireland",
  eire: "Ireland",
  irlanda: "Ireland",
  irlande: "Ireland",
  "northern ireland": "Ireland",
  belgium: "Belgium",
  belgique: "Belgium",
  belgien: "Belgium",
  belgie: "Belgium",
  belgi: "Belgium",
  bulgaria: "Bulgaria",
  austria: "Austria",
  oesterreich: "Austria",
  osterreich: "Austria",
  argentina: "Argentina",
  australia: "Australia",
  australie: "Australia",
  "commonwealth of australia": "Australia",
  bahamas: "Bahamas",
  "commonwealth of the bahamas": "Bahamas",
  brazil: "Brazil",
  brasil: "Brazil",
  canada: "Canada",
  kanada: "Canada",
  "province de quebec": "Canada",
  "province du quebec": "Canada",
  "province of quebec": "Canada",
  colombia: "Colombia",
  croatia: "Croatia",
  hrvatska: "Croatia",
  "czech republic": "Czech Republic",
  czechia: "Czech Republic",
  cesko: "Czech Republic",
  "ceska republika": "Czech Republic",
  denmark: "Denmark",
  danmark: "Denmark",
  "deutscher bund": "Germany",
  "deutsches kaiserreich": "Germany",
  deutschland: "Germany",
  "deutsches reich": "Germany",
  germany: "Germany",
  allemagne: "Germany",
  alemania: "Germany",
  alemanha: "Germany",
  germania: "Germany",
  "german confederation": "Germany",
  "german empire": "Germany",
  espana: "Spain",
  espagne: "Spain",
  spain: "Spain",
  france: "France",
  francia: "France",
  frankreich: "France",
  "heiliges romisches reich": "Germany",
  "heiliges romisches reich deutscher nation": "Germany",
  "holy roman empire": "Germany",
  hungary: "Hungary",
  italy: "Italy",
  italia: "Italy",
  "ivory coast": "Cote d'Ivoire",
  luxemburg: "Luxembourg",
  madarsko: "Hungary",
  macedonia: "North Macedonia",
  magyarorszag: "Hungary",
  mexico: "Mexico",
  mexique: "Mexico",
  netherlands: "Netherlands",
  holland: "Netherlands",
  niederlande: "Netherlands",
  nederland: "Netherlands",
  "koninkrijk der nederlanden": "Netherlands",
  "republiek der zeven verenigde nederlanden": "Netherlands",
  "new zealand": "New Zealand",
  "new zealand colony": "New Zealand",
  aotearoa: "New Zealand",
  "aotearoa new zealand": "New Zealand",
  neuseeland: "New Zealand",
  "nouvelle zelande": "New Zealand",
  "nuova zelanda": "New Zealand",
  "nueva zelanda": "New Zealand",
  "nya zeeland": "New Zealand",
  norway: "Norway",
  noreg: "Norway",
  norge: "Norway",
  "north german confederation": "Germany",
  poland: "Poland",
  polen: "Poland",
  polska: "Poland",
  portugal: "Portugal",
  preussen: "Germany",
  prussia: "Germany",
  russia: "Russia",
  rossiya: "Russia",
  slovensko: "Slovakia",
  "south africa": "South Africa",
  "afrique du sud": "South Africa",
  kaapkolonie: "South Africa",
  "unie van suid afrika": "South Africa",
  "de caep de goede hoop": "South Africa",
  "cape of good hope": "South Africa",
  "suid afrika": "South Africa",
  "zuid afrika": "South Africa",
  schweiz: "Switzerland",
  suiza: "Switzerland",
  suisse: "Switzerland",
  svizzera: "Switzerland",
  suomi: "Finland",
  finland: "Finland",
  sweden: "Sweden",
  suede: "Sweden",
  sverige: "Sweden",
  swaziland: "Eswatini",
  switzerland: "Switzerland",
  "east timor": "Timor-Leste",
  "free state of prussia": "Germany",
  "kingdom of prussia": "Germany",
  burma: "Myanmar",
  "cape verde": "Cabo Verde",
  yugoslavia: "Yugoslavia",
  jugoslavija: "Yugoslavia",
  jugoslawien: "Yugoslavia",
};

export const US_STATE_ALIAS_TO_NAME = {
  mass: "Massachusetts",
  "massachusetts bay": "Massachusetts",
  "massachusetts bay colony": "Massachusetts",
  "colony of massachusetts bay": "Massachusetts",
  "massachusetts colony": "Massachusetts",
  "province of massachusetts": "Massachusetts",
  "province of massachusetts bay": "Massachusetts",
  "province of the massachusetts bay": "Massachusetts",
  "province of m bay": "Massachusetts",
  "province of m bay colony": "Massachusetts",
  "m bay colony": "Massachusetts",
  "m b colony": "Massachusetts",
  "connecticut colony": "Connecticut",
  "colony of connecticut": "Connecticut",
  "new haven colony": "Connecticut",
  "rhode island and providence plantations": "Rhode Island",
  "colony of rhode island and providence plantations": "Rhode Island",
  "providence plantations": "Rhode Island",
  "district of maine": "Maine",
  "maine district": "Maine",
  "east jersey": "New Jersey",
  "west jersey": "New Jersey",
  "republic of texas": "Texas",
  "vermont republic": "Vermont",
  "east florida": "Florida",
  "west florida": "Florida",
  "plymouth colony": "Massachusetts",
};

export const HISTORICAL_US_MARKERS = new Set([
  "bay",
  "colony",
  "commonwealth",
  "district",
  "province",
  "republic",
  "state",
  "territory",
]);

export const HARD_REJECT_UK_COUNTRY_LABELS = new Set(["England", "Northern Ireland", "Scotland", "Wales"]);

export const UK_BIRTH_COUNTY_NATION_ADJECTIVES = { England: "English", Scotland: "Scottish", Wales: "Welsh" };

/** Adjacent historic county pairs, keyed by UK nation. Pair keys are the two names sorted and joined with a pipe. */
export const UK_ADJACENT_BIRTH_COUNTY_PAIRS_BY_NATION = {
  England: new Set([
    "Bedfordshire|Buckinghamshire",
    "Bedfordshire|Cambridgeshire",
    "Bedfordshire|Hertfordshire",
    "Bedfordshire|Huntingdonshire",
    "Bedfordshire|Northamptonshire",
    "Berkshire|Buckinghamshire",
    "Berkshire|Hampshire",
    "Berkshire|Middlesex",
    "Berkshire|Oxfordshire",
    "Berkshire|Surrey",
    "Berkshire|Wiltshire",
    "Buckinghamshire|Hertfordshire",
    "Buckinghamshire|Middlesex",
    "Buckinghamshire|Northamptonshire",
    "Buckinghamshire|Oxfordshire",
    "Cambridgeshire|Essex",
    "Cambridgeshire|Hertfordshire",
    "Cambridgeshire|Huntingdonshire",
    "Cambridgeshire|Lincolnshire",
    "Cambridgeshire|Norfolk",
    "Cambridgeshire|Northamptonshire",
    "Cambridgeshire|Suffolk",
    "Cheshire|Derbyshire",
    "Cheshire|Lancashire",
    "Cheshire|Shropshire",
    "Cheshire|Staffordshire",
    "Cornwall|Devon",
    "Cumberland|Durham",
    "Cumberland|Northumberland",
    "Cumberland|Westmorland",
    "Derbyshire|Lancashire",
    "Derbyshire|Leicestershire",
    "Derbyshire|Nottinghamshire",
    "Derbyshire|Staffordshire",
    "Derbyshire|Yorkshire",
    "Devon|Dorset",
    "Devon|Somerset",
    "Dorset|Hampshire",
    "Dorset|Somerset",
    "Dorset|Wiltshire",
    "Durham|Northumberland",
    "Durham|Westmorland",
    "Durham|Yorkshire",
    "Essex|Hertfordshire",
    "Essex|Middlesex",
    "Essex|Suffolk",
    "Gloucestershire|Herefordshire",
    "Gloucestershire|Oxfordshire",
    "Gloucestershire|Somerset",
    "Gloucestershire|Warwickshire",
    "Gloucestershire|Wiltshire",
    "Gloucestershire|Worcestershire",
    "Hampshire|Surrey",
    "Hampshire|Sussex",
    "Hampshire|Wiltshire",
    "Herefordshire|Shropshire",
    "Herefordshire|Worcestershire",
    "Hertfordshire|Middlesex",
    "Huntingdonshire|Northamptonshire",
    "Kent|Surrey",
    "Kent|Sussex",
    "Lancashire|Westmorland",
    "Lancashire|Yorkshire",
    "Leicestershire|Lincolnshire",
    "Leicestershire|Northamptonshire",
    "Leicestershire|Nottinghamshire",
    "Leicestershire|Rutland",
    "Leicestershire|Staffordshire",
    "Leicestershire|Warwickshire",
    "Lincolnshire|Northamptonshire",
    "Lincolnshire|Nottinghamshire",
    "Lincolnshire|Rutland",
    "Lincolnshire|Yorkshire",
    "Middlesex|Surrey",
    "Norfolk|Suffolk",
    "Northamptonshire|Oxfordshire",
    "Northamptonshire|Rutland",
    "Northamptonshire|Warwickshire",
    "Nottinghamshire|Yorkshire",
    "Oxfordshire|Warwickshire",
    "Oxfordshire|Wiltshire",
    "Shropshire|Staffordshire",
    "Shropshire|Worcestershire",
    "Somerset|Wiltshire",
    "Staffordshire|Warwickshire",
    "Staffordshire|Worcestershire",
    "Surrey|Sussex",
    "Warwickshire|Worcestershire",
    "Westmorland|Yorkshire",
  ]),
  Scotland: new Set([
    "Aberdeenshire|Angus",
    "Aberdeenshire|Banffshire",
    "Aberdeenshire|Inverness-shire",
    "Aberdeenshire|Kincardineshire",
    "Aberdeenshire|Perthshire",
    "Angus|Kincardineshire",
    "Angus|Perthshire",
    "Argyll|Ayrshire",
    "Argyll|Dunbartonshire",
    "Argyll|Inverness-shire",
    "Argyll|Perthshire",
    "Ayrshire|Lanarkshire",
    "Ayrshire|Renfrewshire",
    "Banffshire|Inverness-shire",
    "Banffshire|Morayshire",
    "Berwickshire|East Lothian",
    "Berwickshire|Midlothian",
    "Berwickshire|Roxburghshire",
    "Caithness|Sutherland",
    "Clackmannanshire|Fife",
    "Clackmannanshire|Perthshire",
    "Clackmannanshire|Stirlingshire",
    "Dumfriesshire|Kirkcudbrightshire",
    "Dumfriesshire|Lanarkshire",
    "Dumfriesshire|Peeblesshire",
    "Dumfriesshire|Roxburghshire",
    "Dumfriesshire|Selkirkshire",
    "Dunbartonshire|Lanarkshire",
    "Dunbartonshire|Perthshire",
    "Dunbartonshire|Renfrewshire",
    "Dunbartonshire|Stirlingshire",
    "East Lothian|Midlothian",
    "Fife|Kinross-shire",
    "Fife|Perthshire",
    "Inverness-shire|Morayshire",
    "Inverness-shire|Nairnshire",
    "Inverness-shire|Perthshire",
    "Inverness-shire|Ross-shire",
    "Inverness-shire|Sutherland",
    "Kinross-shire|Perthshire",
    "Kirkcudbrightshire|Wigtownshire",
    "Lanarkshire|Midlothian",
    "Lanarkshire|Peeblesshire",
    "Lanarkshire|Renfrewshire",
    "Lanarkshire|Stirlingshire",
    "Lanarkshire|West Lothian",
    "Midlothian|Peeblesshire",
    "Midlothian|Roxburghshire",
    "Midlothian|Selkirkshire",
    "Midlothian|West Lothian",
    "Morayshire|Nairnshire",
    "Peeblesshire|Selkirkshire",
    "Perthshire|Stirlingshire",
    "Ross-shire|Sutherland",
    "Roxburghshire|Selkirkshire",
    "Stirlingshire|West Lothian",
  ]),
  Wales: new Set([
    "Brecknockshire|Cardiganshire",
    "Brecknockshire|Carmarthenshire",
    "Brecknockshire|Glamorgan",
    "Brecknockshire|Monmouthshire",
    "Brecknockshire|Montgomeryshire",
    "Brecknockshire|Radnorshire",
    "Caernarfonshire|Denbighshire",
    "Caernarfonshire|Merionethshire",
    "Cardiganshire|Carmarthenshire",
    "Cardiganshire|Merionethshire",
    "Cardiganshire|Montgomeryshire",
    "Cardiganshire|Pembrokeshire",
    "Carmarthenshire|Glamorgan",
    "Carmarthenshire|Pembrokeshire",
    "Denbighshire|Flintshire",
    "Denbighshire|Merionethshire",
    "Denbighshire|Montgomeryshire",
    "Glamorgan|Monmouthshire",
    "Merionethshire|Montgomeryshire",
    "Montgomeryshire|Radnorshire",
  ]),
};
