export const firstNameVariants = {
  Aaltje: ["Aaltje", "Aalt"],
  Aaron: ["Aaron", "Ron", "Ronnie"],
  Abigail: ["Abigail", "Abby", "Gail"],
  Ada: ["Ada", "Adina"],
  Adam: ["Adam", "Ad", "Addy", "Adie"],
  Adelaide: ["Adelaide", "Ada"],
  Adelina: ["Adelina", "Adeline", "Lina"],
  Adeline: ["Adeline", "Adelina", "Adele", "Adela"],
  Adolphe: ["Adolphe", "Adolf", "Adolfo"],
  Adriaan: ["Adriaan", "Adrian", "Aad"],
  Adriana: ["Adriana", "Adrianne", "Ariana"],
  Adrien: ["Adrien", "Adrian", "Adrián"],
  Agatha: ["Agatha", "Agathe", "Aggie"],
  Agathe: ["Agathe", "Agatha", "Agata"],
  Agnes: ["Agnes", "Aggie"],
  Agostina: ["Agostina", "Augusta"],
  Aida: ["Aida", "Aide"],
  Aime: ["Aime", "Aimé"],
  Alain: ["Alain", "Alan"],
  Alan: ["Alan", "Al"],
  Albert: ["Albert", "Al", "Bert", "Alberto"],
  Alberta: ["Alberta", "Alberte"],
  Alessandra: ["Alessandra", "Alexandra"],
  Alessandro: ["Alessandro", "Alexander"],
  Alex: ["Alex", "Alejandro", "Alexander"],
  Alexander: ["Alexander", "Alex", "Alec", "Xander", "Sandy", "Sasha", "Sash"],
  Alexandre: ["Alexandre", "Alexander", "Alejandro", "Aleksandr"],
  Alfred: ["Alfred", "Alfie", "Fred", "Freddy", "Freddie"],
  Alfredo: ["Alfredo", "Alfie"],
  Alice: ["Alice", "Allie", "Ally", "Alicia", "Alix"],
  Alida: ["Alida", "Alyda"],
  Aline: ["Aline", "Alina"],
  Amadeo: ["Amadeo", "Amadeus"],
  Amanda: ["Amanda", "Mandy"],
  Amandine: ["Amandine", "Amanda"],
  Amelia: ["Amelia", "Emilia", "Amy", "Amelie"],
  Amélie: ["Amélie", "Amelia"],
  Amico: ["Amico", "Amicus"],
  André: ["André", "Andre", "Andrés"],
  Andrea: ["Andrea", "Andrew"],
  Andrew: ["Andrew", "Andy", "Drew"],
  Ange: ["Ange", "Angel"],
  Angela: ["Angela", "Angie"],
  Angélique: ["Angélique", "Angelica"],
  Angelo: ["Angelo", "Angel"],
  Ann: ["Ann", "Annie", "Anne", "Anna"],
  Anna: ["Anna", "Anne", "Ann", "Annie", "Annette"],
  Anne: ["Anne", "Anna", "Anna", "Anne", "Ann", "Annie", "Annette"],
  Anthony: ["Anthony", "Tony", "Ant", "Antony"],
  Antoine: ["Antoine", "Antonio"],
  Antonia: ["Antonia", "Tonia"],
  Antonio: ["Antonio", "Tony"],
  Ariana: ["Ariana", "Ariane"],
  Arianna: ["Arianna", "Arianne"],
  Arie: ["Arie", "Ari", "Ary"],
  Armand: ["Armand", "Armando"],
  Armando: ["Armando", "Armand"],
  Arthur: ["Arthur", "Art", "Artie"],
  Arturo: ["Arturo", "Arthur"],
  Assunta: ["Assunta", "Assumpta"],
  Augusta: ["Augusta", "Augustina", "Gussie"],
  Aurélie: ["Aurélie", "Aurelia"],
  Aurora: ["Aurora", "Rory"],
  Baptiste: ["Baptiste", "Baptista"],
  Barbe: ["Barbe", "Barbara"],
  Bart: ["Bart", "Baart", "Barte"],
  Basile: ["Basile", "Basil"],
  Béatrice: ["Béatrice", "Beatrice"],
  Beatrice: ["Beatrice", "Beatrix"],
  Benedetta: ["Benedetta", "Benedicta"],
  Benedetto: ["Benedetto", "Benedict"],
  Bénédicte: ["Bénédicte", "Benedicta"],
  Benjamin: ["Benjamin", "Ben", "Benny"],
  Benno: ["Benno", "Benneke"],
  Bernard: ["Bernard", "Bernardo"],
  Bernice: ["Bernice", "Bernie"],
  Bertrand: ["Bertrand", "Bertrando"],
  Beth: ["Beth", "Betsy"],
  Betty: ["Betty", "Bettie"],
  Beverly: ["Beverly", "Bev"],
  Bianca: ["Bianca", "Blanche"],
  Blaise: ["Blaise", "Blas"],
  Blanche: ["Blanche", "Blannie"],
  Bonnie: ["Bonnie", "Bonnie"],
  Brad: ["Brad", "Bradley"],
  Brandon: ["Brandon", "Brandy"],
  Brenda: ["Brenda", "Bren"],
  Brian: ["Brian", "Bryan"],
  Brittany: ["Brittany", "Britt"],
  Brooke: ["Brooke", "Brookie"],
  Bruce: ["Bruce", "Brucie"],
  Bruno: ["Bruno"],
  Caitlyn: ["Caitlyn", "Katie"],
  Calvin: ["Calvin", "Cal"],
  Camila: ["Camila", "Camille"],
  Camille: ["Camille", "Camila"],
  Carl: ["Carl", "Karl"],
  Carlo: ["Carlo", "Carlos"],
  Carlotta: ["Carlotta", "Carla"],
  Carmen: ["Carmen", "Caroline"],
  Carmine: ["Carmine", "Carmino"],
  Carol: ["Carol", "Carrie"],
  Carolina: ["Carolina", "Caroline"],
  Caroline: ["Caroline", "Carolina", "Carolyn"],
  Casimiro: ["Casimiro", "Casimir"],
  Cassandra: ["Cassandra", "Cassie"],
  Caterina: ["Caterina", "Katherine"],
  Catherine: ["Catherine", "Katharine", "Katarina", "Kathy", "Kate", "Katie", "Cathy", "Cathie", "Cath"],
  Cécile: ["Cécile", "Cecilia"],
  Celeste: ["Celeste", "Celestine"],
  Celia: ["Celia", "Cece", "Celie"],
  Céline: ["Céline", "Celina"],
  Cesare: ["Cesare", "Caesar"],
  Cesarina: ["Cesarina", "Caesarine"],
  Chad: ["Chad", "Chadwick"],
  Chandler: ["Chandler", "Chan"],
  Charles: ["Charles", "Carlos", "Carlo", "Charlie", "Charley", "Chuck", "Chas", "Chaz"],
  Charlotte: ["Charlotte", "Lottie", "Lottie", "Carlota"],
  Chas: ["Chas", "Charles"],
  Cheryl: ["Cheryl", "Cherie"],
  Chiara: ["Chiara", "Claire"],
  Chiarina: ["Chiarina", "Clare"],
  Chloé: ["Chloé", "Chloe"],
  Christian: ["Christian", "Cristiano", "Chris"],
  Christina: ["Christina", "Tina"],
  Christine: ["Christine", "Cristina", "Chris"],
  Christopher: ["Christopher", "Chris", "Kit"],
  Cinzia: ["Cinzia", "Cynthia"],
  Claire: ["Claire", "Clare"],
  Clara: ["Clara", "Claire"],
  Claude: ["Claude"],
  Claudio: ["Claudio", "Claudius"],
  Clayton: ["Clayton", "Clay"],
  Clément: ["Clément", "Clemente"],
  Clementina: ["Clementina", "Clementine"],
  Cleto: ["Cleto", "Cletus"],
  Clifford: ["Clifford", "Cliff"],
  Cody: ["Cody", "Codey"],
  Colette: ["Colette"],
  Colleen: ["Colleen", "Collie"],
  Collette: ["Collette", "Coleta"],
  Colombo: ["Colombo", "Columbus"],
  Concetta: ["Concetta", "Conception"],
  Concetto: ["Concetto", "Conceptus"],
  Connie: ["Connie", "Con"],
  Constance: ["Constance", "Connie", "Constanca", "Constanza"],
  Constanza: ["Constanza", "Constance"],
  Coralie: ["Coralie", "Coralia"],
  Corentin: ["Corentin", "Corentine"],
  Cornelis: ["Cornelis", "Cornelius", "Kees"],
  Corrado: ["Corrado", "Corradino"],
  Cosimo: ["Cosimo", "Cosme"],
  Craig: ["Craig", "Craggy"],
  Cristiano: ["Cristiano", "Cristian"],
  Crystal: ["Crystal", "Crys"],
  Curtis: ["Curtis", "Curt"],
  Cynthia: ["Cynthia", "Cindy"],
  Cyrille: ["Cyrille", "Cirilo"],
  Daan: ["Daan", "Daniel", "Dani"],
  Dale: ["Dale", "Dailey"],
  Damian: ["Damian", "Damien"],
  Damien: ["Damien"],
  Dana: ["Dana", "Danny"],
  Daniel: ["Daniel", "Dan", "Danny", "Dani", "Daniele"],
  Daniele: ["Daniele", "Daniel", "Danny"],
  Dante: ["Dante", "Dan"],
  Dario: ["Dario", "Darrio"],
  Darlene: ["Darlene", "Darlie"],
  Dave: ["Dave", "David"],
  David: ["David", "Dave", "Davide"],
  Dawn: ["Dawn", "Donna"],
  Dean: ["Dean", "Deano"],
  Deanna: ["Deanna", "Diana"],
  Debora: ["Debora", "Debra", "Deb"],
  Delfina: ["Delfina", "Delphine"],
  Delphine: ["Delphine", "Delfina"],
  Denis: ["Denis", "Denny", "Den"],
  Denise: ["Denise", "Deni"],
  Dennis: ["Dennis", "Denny"],
  Derek: ["Derek", "Derick"],
  Derrick: ["Derrick", "Derrick"],
  Desmond: ["Desmond", "Des"],
  Diana: ["Diana", "Di"],
  Diane: ["Diane", "Di"],
  Dick: ["Dick", "Richard"],
  Dirk: ["Dirk", "Dirkje"],
  Dixie: ["Dixie", "Dix"],
  Dolores: ["Dolores", "Lola"],
  Domenico: ["Domenico", "Domenique"],
  Domingo: ["Domingo", "Dom"],
  Donatella: ["Donatella", "Donna"],
  Donna: ["Donna", "Don"],
  Doris: ["Doris", "Doreen"],
  Dorothy: ["Dorothy", "Dot"],
  Doug: ["Doug", "Douglas"],
  Douglas: ["Douglas", "Doug"],
  Dulce: ["Dulce", "Dulcie"],
  Dustin: ["Dustin", "Dusty"],
  Dylan: ["Dylan", "Dyllan"],
  Earl: ["Earl", "Earle"],
  Ed: ["Ed", "Eddie"],
  Edda: ["Edda", "Eddie"],
  Eddie: ["Eddie", "Ed"],
  Edith: ["Edith", "Edie"],
  Edmund: ["Edmund", "Ed"],
  Edouard: ["Edouard", "Edward", "Eddie"],
  Eduardo: ["Eduardo", "Eddie"],
  Edward: ["Edward", "Ed", "Eddie", "Edouard", "Eduardo", "Ned"],
  Edwin: ["Edwin", "Ed"],
  Elaine: ["Elaine", "Laine"],
  Eleanor: ["Eleanor", "Ellie"],
  Elena: ["Elena", "Helen", "Lena"],
  Eleonora: ["Eleonora", "Eleanor"],
  Elia: ["Elia", "Eli"],
  Elio: ["Elio", "Leo"],
  Elisabetta: ["Elisabetta", "Elisabeth"],
  Elizabeth: ["Elizabeth", "Liz", "Beth", "Betty", "Eliza", "Lizzie", "Liza"],
  Ella: ["Ella", "Ellie"],
  Ellen: ["Ellen", "Ella", "Ellie", "Nell", "Nellie", "Nelly", "Lena", "Lennie", "Lennie"],
  Ellie: ["Ellie", "Ella"],
  Eloise: ["Eloise", "Lois"],
  Elsie: ["Elsie", "El"],
  Elton: ["Elton", "Elt"],
  Emanuele: ["Emanuele", "Emmanuel"],
  Emery: ["Emery", "Em"],
  Emil: ["Emil", "Emile"],
  Emile: ["Emile", "Emil", "Emile"],
  Emiliano: ["Emiliano", "Emil"],
  Emily: ["Emily", "Emmy", "Emma"],
  Emma: ["Emma", "Emily"],
  Enrico: ["Enrico", "Henry"],
  Enrique: ["Enrique", "Henry"],
  Eraldo: ["Eraldo", "Ernie"],
  Eric: ["Eric", "Erik"],
  Erica: ["Erica", "Ericka"],
  Erik: ["Erik", "Erike", "Erick"],
  Erin: ["Erin", "Ernie"],
  Ernest: ["Ernest", "Ernie"],
  Ernesto: ["Ernesto", "Ernest"],
  Estelle: ["Estelle", "Stella"],
  Esther: ["Esther", "Essie"],
  Ethan: ["Ethan", "Eathan"],
  Etienne: ["Etienne", "Stephen"],
  Ettore: ["Ettore", "Hector"],
  Eugene: ["Eugene", "Gene"],
  Eugenio: ["Eugenio", "Gene"],
  Eusebio: ["Eusebio", "Eusebius"],
  Eva: ["Eva", "Evie"],
  Evangelista: ["Evangelista", "John the Baptist"],
  Evelyn: ["Evelyn", "Eve"],
  Faith: ["Faith", "Fay"],
  Federico: ["Federico", "Frederick"],
  Felix: ["Felix", "Fel"],
  Ferdinando: ["Ferdinando", "Ferdinand"],
  Fern: ["Fern", "Fernie"],
  Fiammetta: ["Fiammetta", "Pepi"],
  Filiberto: ["Filiberto", "Philip"],
  Filippo: ["Filippo", "Philip"],
  Florence: ["Florence", "Flora"],
  Floriana: ["Floriana", "Flora"],
  Floyd: ["Floyd", "Floy"],
  Frances: ["Frances", "Fran", "Fannie"],
  Francesca: ["Francesca", "Frances"],
  Francesco: ["Francesco", "Francis"],
  Francis: ["Francis", "Fran", "Frank"],
  Frank: ["Frank", "Frankie"],
  Franklin: ["Franklin", "Frank"],
  Frans: ["Frans", "Francis", "Frank"],
  Fred: ["Fred", "Freddy"],
  Frederick: ["Frederick", "Fred"],
  Gabriel: ["Gabriel", "Gabe", "Gabby"],
  Gabriela: ["Gabriela", "Gabi"],
  Gabriella: ["Gabriella", "Gabi"],
  Gabrielle: ["Gabrielle", "Gabi"],
  Gail: ["Gail", "Gayle"],
  Gary: ["Gary", "Gaz"],
  Gaspare: ["Gaspare", "Jasper"],
  Gaudenzio: ["Gaudenzio", "Gonzalo"],
  Gavino: ["Gavino", "Gavin"],
  Geneva: ["Geneva", "Genny"],
  Genevieve: ["Genevieve", "Genevieve", "Genie"],
  Geoffrey: ["Geoffrey", "Jeffrey", "Geoff"],
  George: ["George", "Geo", "Geordie", "Geoff"],
  Georges: ["Georges", "George", "Geo"],
  Gerald: ["Gerald", "Gerry"],
  Germain: ["Germain", "German"],
  Gerrit: ["Gerrit", "Gerritt", "Gert"],
  Giancarlo: ["Giancarlo", "John"],
  Gianni: ["Gianni", "John"],
  Gilbert: ["Gilbert", "Gil"],
  Gilles: ["Gilles", "Gill"],
  Gillian: ["Gillian", "Jill"],
  Ginevra: ["Ginevra", "Genevieve"],
  Giorgia: ["Giorgia", "Georgia"],
  Giovanna: ["Giovanna", "Joan"],
  Giovanni: ["Giovanni", "John"],
  Gisella: ["Gisella", "Giselle"],
  Giselle: ["Giselle", "Giselle"],
  Giuseppe: ["Giuseppe", "Joseph"],
  Gladys: ["Gladys", "Gladdy"],
  Glen: ["Glen", "Glenn"],
  Glenda: ["Glenda", "Glen"],
  Glenn: ["Glenn", "Glen"],
  Gloria: ["Gloria", "Glory"],
  Gordon: ["Gordon", "Gordy"],
  Grace: ["Grace", "Gracie"],
  Graham: ["Graham", "Graeme"],
  Grant: ["Grant", "Granny"],
  Gray: ["Gray", "Grey"],
  Grazia: ["Grazia", "Grace"],
  Graziano: ["Graziano", "Grace"],
  Greg: ["Greg", "Gregory"],
  Gregorio: ["Gregorio", "Gregory"],
  Gregory: ["Gregory", "Greg"],
  Greta: ["Greta", "Gretchen"],
  Guido: ["Guido", "Guy"],
  Guillaume: ["Guillaume", "William", "Guill"],
  Guillermo: ["Guillermo", "Will"],
  Gus: ["Gus", "Augustus"],
  Gussie: ["Gussie", "Guss"],
  Guy: ["Guy", "Guido"],
  Gwen: ["Gwen", "Gwendolyn"],
  Hannah: ["Hannah", "Anna", "Hanna"],
  Hans: ["Hans", "Johannes", "Jan"],
  Harold: ["Harold", "Hal", "Harry"],
  Harrison: ["Harrison", "Harry"],
  Harry: ["Harry", "Hal", "Henry", "Hank"],
  Harvey: ["Harvey", "Harv"],
  Hayden: ["Hayden", "Haydn"],
  Heather: ["Heather", "Heth"],
  Heidi: ["Heidi", "Hedy"],
  Helen: ["Helen", "Nell"],
  Hendrik: ["Hendrik", "Henry", "Henk"],
  Henri: ["Henri", "Henry"],
  Henry: ["Henry", "Harry", "Hal", "Hank"],
  Herbert: ["Herbert", "Bert", "Bertie", "Herb"],
  Hester: ["Hester", "Hessie"],
  Holly: ["Holly", "Hollie"],
  Honore: ["Honore", "Honor"],
  Hope: ["Hope", "Hopie"],
  Howard: ["Howard", "Howie"],
  Hubert: ["Hubert", "Hub"],
  Hugh: ["Hugh", "Hugo"],
  Hugo: ["Hugo", "Hugh"],
  Iacopo: ["Iacopo", "James"],
  Ian: ["Ian", "Iain"],
  Ida: ["Ida", "Idie"],
  Ignazio: ["Ignazio", "Ignatius"],
  Ilaria: ["Ilaria", "Hilary"],
  Imogen: ["Imogen", "Immy"],
  Ingrid: ["Ingrid", "Inga"],
  Irene: ["Irene", "Rena"],
  Irina: ["Irina", "Rina"],
  Iris: ["Iris", "Irish"],
  Irma: ["Irma", "Irmie"],
  Irvin: ["Irvin", "Irvine"],
  Isaac: ["Isaac", "Ike"],
  Isabel: ["Isabel", "Izzy"],
  Isabella: ["Isabella", "Isa", "Izzy", "Bella"],
  Isadora: ["Isadora", "Dora"],
  Isidore: ["Isidore", "Issy"],
  Jack: ["Jack", "John", "Johnny"],
  Jackie: ["Jackie", "Jack"],
  Jackson: ["Jackson", "Jack"],
  Jacob: ["Jacob", "Jake"],
  Jacopo: ["Jacopo", "Giacomo", "Giacopo"],
  Jacqueline: ["Jacqueline", "Jacque"],
  Jacques: ["Jacques", "James", "Jack"],
  Jakob: ["Jakob", "Jacobus", "Jacques"],
  James: ["James", "Jim", "Jem", "Jamie", "Jimmy", "Jimmie"],
  Jan: ["Jan", "Johan", "John"],
  Jane: ["Jane", "Jenny", "Jennie", "Janey", "Janie"],
  Janet: ["Janet", "Jan"],
  Janice: ["Janice", "Jan"],
  Jared: ["Jared", "Jar", "Jerry", "Jed"],
  Jason: ["Jason", "Jace"],
  Jean: ["Jean", "Jeannie"],
  Jeanne: ["Jeanne", "Jan"],
  Jeannette: ["Jeannette", "Janet"],
  Jeff: ["Jeff", "Jeffrey"],
  Jefferson: ["Jefferson", "Jeff"],
  Jeffrey: ["Jeffrey", "Jeff"],
  Jemima: ["Jemima", "Jim"],
  Jenna: ["Jenna", "Jen"],
  Jennifer: ["Jennifer", "Jenny"],
  Jeremiah: ["Jeremiah", "Jerry"],
  Jeremy: ["Jeremy", "Jerry"],
  Jesse: ["Jesse", "Jess"],
  Jessica: ["Jessica", "Jess"],
  Jessie: ["Jessie", "Jess"],
  Jill: ["Jill", "Jillian"],
  Joan: ["Joan", "Jo"],
  Joanna: ["Joanna", "Joan", "Jo"],
  Joanne: ["Joanne", "Jo"],
  Jocelyn: ["Jocelyn", "Jocelyne", "Jocasta", "Jo"],
  Jodie: ["Jodie", "Jody"],
  Joel: ["Joel", "Joe"],
  Joey: ["Joey", "Joe"],
  John: ["John", "Jack", "Johnny", "Jon", "Jonny"],
  Johnny: ["Johnny", "John"],
  Jonathan: ["Jonathan", "Jon"],
  Jones: ["Jones", "Jon"],
  Jordan: ["Jordan", "Jordy"],
  Joseph: ["Joseph", "Joe", "Joey", "Josie", "Josiah"],
  Josh: ["Josh", "Joshua"],
  Joshua: ["Joshua", "Josh"],
  Josiah: ["Josiah", "Josh"],
  Joy: ["Joy", "Joyce"],
  Joyce: ["Joyce", "Joy"],
  Juan: ["Juan", "John"],
  Judith: ["Judith", "Judy"],
  Judy: ["Judy", "Judith"],
  Jules: ["Jules", "Julius"],
  Julia: ["Julia", "Julie"],
  Julian: ["Julian", "Julius"],
  Julie: ["Julie", "Julia"],
  Julius: ["Julius", "Jules"],
  June: ["June", "Junie"],
  Justin: ["Justin", "Just"],
  Karen: ["Karen", "Kar"],
  Kate: ["Kate", "Kathy"],
  Katherine: ["Katherine", "Kathy", "Kate", "Katie"],
  Kathleen: ["Kathleen", "Katie"],
  Klaas: ["Klaas", "Nicolaas", "Nico"],
  Lauren: ["Lauren", "Laurie"],
  Leo: ["Leo", "Leon"],
  Leopold: ["Leopold", "Leo"],
  Liliane: ["Liliane", "Lilian"],
  Lillian: ["Lillian", "Lily", "Lilly", "Lillie"],
  Lorenzo: ["Lorenzo", "Renzo"],
  Louis: ["Louis", "Lewis"],
  Luc: ["Luc", "Luke"],
  Luca: ["Luca", "Luigi"],
  Lucia: ["Lucia", "Lucy"],
  Lucie: ["Lucie", "Lucy"],
  Madeleine: ["Madeleine", "Maddy"],
  Manuela: ["Manuela", "Manuel", "Nell"],
  Marcello: ["Marcello", "Marcel"],
  Margaret: ["Margaret", "Maggie", "Meg"],
  Margaux: ["Margaux", "Margaret"],
  Marie: ["Marie", "Mary"],
  Marina: ["Marina", "Mari"],
  Marthe: ["Marthe", "Martha"],
  Martijn: ["Martijn", "Marten", "Martine"],
  Martina: ["Martina", "Marta", "Marty"],
  Martine: ["Martine", "Martina"],
  Mary: ["Mary", "Mollie", "Polly", "Molly", "Moll"],
  Massimo: ["Massimo", "Max"],
  Matteo: ["Matteo", "Matt"],
  Matthew: ["Matthew", "Mat"],
  Maurizio: ["Maurizio", "Mauro"],
  Maxime: ["Maxime", "Max"],
  Michael: ["Michael", "Mike"],
  Michelle: ["Michelle", "Michel"],
  Michiel: ["Michiel", "Michel", "Michael"],
  Mirella: ["Mirella", "Miriam"],
  Natalina: ["Natalina", "Natalie", "Nataly"],
  Nathalie: ["Nathalie", "Natalie"],
  Nathaniel: ["Nathaniel", "Nate", "Nat"],
  Nicholas: ["Nicholas", "Nick", "Nico", "Nicky", "Nik"],
  Nico: ["Nico", "Nick"],
  Nicolò: ["Nicolò", "Nicol"],
  Niels: ["Niels", "Cornelius", "Cornel"],
  Noelle: ["Noelle", "Noel"],
  Noemi: ["Noemi", "Naomi"],
  Olga: ["Olga", "Oly"],
  Oliver: ["Oliver", "Ollie"],
  Olivier: ["Olivier", "Ollie"],
  Oscar: ["Oscar", "Ossie"],
  Paolo: ["Paolo", "Paul"],
  Pascal: ["Pascal", "Pascal"],
  Patricia: ["Patricia", "Pat", "Patsy", "Patty"],
  Patrick: ["Patrick", "Pat", "Paddy", "Patsy", "Patty"],
  Paul: ["Paul", "Pauly", "Pablo", "Paule"],
  Penelope: ["Penelope", "Penny"],
  Percy: ["Percy", "Perce"],
  Peter: ["Peter", "Pete", "Petey"],
  Philip: ["Philip", "Phil"],
  Philippa: ["Philippa", "Pippa"],
  Phillip: ["Phillip", "Phil"],
  Phoebe: ["Phoebe", "Phebe"],
  Phyllis: ["Phyllis", "Phyl"],
  Pierre: ["Pierre", "Pete", "Piet", "Pietro", "Peter"],
  Pieter: ["Pieter", "Peter", "Piet"],
  Pietro: ["Pietro", "Peter"],
  Polly: ["Polly", "Molly"],
  Priscilla: ["Priscilla", "Cilla"],
  Rachel: ["Rachel", "Rach", "Rachael", "Rachelle", "Rae"],
  Raffaele: ["Raffaele", "Rafael"],
  Ralph: ["Ralph", "Rafe", "Ralf"],
  Randy: ["Randy", "Randall"],
  Raphaël: ["Raphaël", "Raph"],
  Raymond: ["Raymond", "Ray", "Raymund"],
  Rebecca: ["Rebecca", "Becky", "Becca"],
  Regina: ["Regina", "Gina"],
  Reginald: ["Reginald", "Reg", "Reggie"],
  Reinier: ["Reinier", "Regnerus"],
  Renaud: ["Renaud", "Ren"],
  Rene: ["Rene", "Ren"],
  René: ["René", "Rene"],
  Riccardo: ["Riccardo", "Ricardo"],
  Richard: ["Richard", "Rich", "Dick", "Rick"],
  Robert: ["Robert", "Rob", "Robt", "Bob", "Bobby"],
  Roberto: ["Roberto", "Rob", "Robt", "Bert", "Bobby"],
  Robin: ["Robin", "Robyn"],
  Roch: ["Roch", "Rock"],
  Roger: ["Roger", "Rodger", "Rog"],
  Roland: ["Roland", "Rollie", "Rolly"],
  Romain: ["Romain", "Roman"],
  Ronald: ["Ronald", "Ron", "Ronnie"],
  Rory: ["Rory", "Rorie"],
  Rosa: ["Rosa", "Rose"],
  Rosalind: ["Rosalind", "Linda"],
  Rosamund: ["Rosamund", "Rosa"],
  Rose: ["Rose", "Rosie", "Rosa", "Roz"],
  Ross: ["Ross", "Roscoe"],
  Rowena: ["Rowena", "Rona"],
  Roy: ["Roy", "King"],
  Roy: ["Roy", "LeRoy"],
  Ruben: ["Ruben", "Ruby"],
  Ruby: ["Ruby", "Rubes"],
  Rupert: ["Rupert", "Rupes"],
  Russell: ["Russell", "Russ"],
  Ruth: ["Ruth", "Ruthie"],
  Ryan: ["Ryan", "Ry", "Rye"],
  Sabine: ["Sabine", "Sabrina"],
  Sadie: ["Sadie", "Sade"],
  Sally: ["Sally", "Sallie"],
  Samantha: ["Samantha", "Sam", "Sammie", "Sammy"],
  Samuel: ["Samuel", "Sam", "Sammy"],
  Sander: ["Sander", "Sandor"],
  Sandra: ["Sandra", "Sandy"],
  Sandrine: ["Sandrine", "Sandy"],
  Sandy: ["Sandy", "Sande"],
  Sara: ["Sara", "Sarah"],
  Sarah: ["Sarah", "Sally", "Sara", "Sarrah"],
  Saul: ["Saul", "Sol"],
  Scott: ["Scott", "Scot"],
  Sebastian: ["Sebastian", "Seb"],
  Selena: ["Selena", "Lena"],
  Selina: ["Selina", "Lina"],
  Serena: ["Serena", "Serene"],
  Serge: ["Serge", "Sergio"],
  Seymour: ["Seymour", "Morey"],
  Shane: ["Shane", "Shayn"],
  Sharon: ["Sharon", "Shaz"],
  Shaun: ["Shaun", "Shawn"],
  Shawn: ["Shawn", "Sean"],
  Shea: ["Shea", "Shay"],
  Sheena: ["Sheena", "Neena"],
  Shelby: ["Shelby", "Shelly"],
  Shelley: ["Shelley", "Shelly"],
  Shirley: ["Shirley", "Shirl"],
  Sidney: ["Sidney", "Sid"],
  Silvia: ["Silvia", "Sylvia"],
  Simon: ["Simon", "Sim"],
  Simona: ["Simona", "Simone"],
  Simone: ["Simone", "Monie"],
  Sjoerd: ["Sjoerd", "Sjurd"],
  Solomon: ["Solomon", "Sol"],
  Sonia: ["Sonia", "Sonny"],
  Sonny: ["Sonny", "Sawney"],
  Sophie: ["Sophie", "Soph"],
  Spencer: ["Spencer", "Spence"],
  Stanley: ["Stanley", "Stan"],
  Stefan: ["Stefan", "Steve"],
  Stefano: ["Stefano", "Steve"],
  Stéphane: ["Stéphane", "Steph"],
  Stephen: ["Stephen", "Steve", "Stevie"],
  Sterling: ["Sterling", "Sterl"],
  Steve: ["Steve", "Stevie"],
  Stewart: ["Stewart", "Stu"],
  Sue: ["Sue", "Suzie"],
  Susan: ["Susan", "Susie", "Suzie", "Sue", "Suz"],
  Susanna: ["Susanna", "Suzy"],
  Susannah: ["Susannah", "Susie"],
  Susie: ["Susie", "Suzie"],
  Suzanne: ["Suzanne", "Suzie"],
  Sybil: ["Sybil", "Sibby"],
  Sydney: ["Sydney", "Sid"],
  Sylvain: ["Sylvain", "Sylvester"],
  Sylvester: ["Sylvester", "Sly"],
  Tad: ["Tad", "Thad"],
  Tamsin: ["Tamsin", "Tammy"],
  Tanguy: ["Tanguy", "Tan"],
  Tania: ["Tania", "Tanya"],
  Teresa: ["Teresa", "Terese", "Tess"],
  Terrance: ["Terrance", "Terry"],
  Terrell: ["Terrell", "Terry"],
  Terrence: ["Terrence", "Terry"],
  Terry: ["Terry", "Terrance"],
  Teunis: ["Teunis", "Antonius", "Tony"],
  Thaddeus: ["Thaddeus", "Thad"],
  Theodore: ["Theodore", "Theo", "Ted"],
  Théodore: ["Théodore", "Theo"],
  Thérèse: ["Thérèse", "Terry"],
  Thibault: ["Thibault", "Tibby"],
  Thierry: ["Thierry", "Terry", "Tyrone"],
  Thomas: ["Thomas", "Tom", "Tommy", "Tommie", "Thom"],
  Timothée: ["Timothée", "Tim"],
  Timothy: ["Timothy", "Tim"],
  Titouan: ["Titouan", "Tit"],
  Titus: ["Titus", "Tite"],
  Toby: ["Toby", "Tobias"],
  Todd: ["Todd", "Tod"],
  Tommy: ["Tommy", "Tom"],
  Tony: ["Tony", "Antonio"],
  Toussaint: ["Toussaint", "Tous"],
  Toussaint: ["Toussaint", "Toussaint"],
  Travis: ["Travis", "Trav"],
  Trent: ["Trent", "Trenton"],
  Trevor: ["Trevor", "Trev"],
  Tristan: ["Tristan", "Tris"],
  Troy: ["Troy", "Troi"],
  Tyler: ["Tyler", "Tyle"],
  Tyrone: ["Tyrone", "Ty"],
  Tyson: ["Tyson", "Tys"],
  Umberto: ["Umberto", "Humbert"],
  Urbain: ["Urbain", "Urby"],
  Uriel: ["Uriel", "Uri"],
  Valentin: ["Valentin", "Val"],
  Valentina: ["Valentina", "Val"],
  Valentine: ["Valentine", "Val"],
  Valérie: ["Valérie", "Val"],
  Véronique: ["Véronique", "Veron"],
  Victor: ["Victor", "Vic"],
  Victoria: ["Victoria", "Vicki", "Vicky"],
  Vincent: ["Vincent", "Vince"],
  Vinciane: ["Vinciane", "Vincy"],
  Virginie: ["Virginie", "Virg"],
  Vittoria: ["Vittoria", "Victoria"],
  Vittorio: ["Vittorio", "Victor"],
  Walter: ["Walter", "Walt", "Wally", "Waltie"],
  Willem: ["Willem", "Wilhelmus", "Wim"],
  William: ["William", "Will", "Bill", "Wm", "Billy", "Willie"],
  Xander: ["Xander", "Alexander"],
  Xavier: ["Xavier", "Xav"],
  Yann: ["Yann", "Yan"],
  Ylenia: ["Ylenia", "Helen"],
  Yves: ["Yves", "Yvon"],
  Yvo: ["Yvo", "Ivo"],
  Zaan: ["Zaan", "Isaac", "Izaak"],
  Zacharie: ["Zacharie", "Zac"],
  Zachary: ["Zachary", "Zach", "Zak", "Zac"],
  Zélie: ["Zélie", "Zelie"],
  Zoe: ["Zoe", "Zoie"],
};
