export const occupationCategories = {
  "Merchant Seaman": {
    Places: ["England"],
    PluralForm: "Merchant Seamen",
    Standalone: false,
  },
  "Insurance Agent": {
    Places: ["England"],
    PluralForm: "Insurance Agents",
    Standalone: true,
  },
  Needlewoman: {
    Places: ["England"],
    PluralForm: "Needlewomen",
    Standalone: false,
  },
  Accountant: {
    Places: ["Australia", "Canada"],
    PluralForm: "Accountants",
    Standalone: true,
  },
  "Chemists And Druggist": {
    Places: ["England"],
    PluralForm: "Chemists and Druggists",
    Standalone: false,
  },
  "Newspaper Reporter": {
    Places: ["England"],
    PluralForm: "Newspaper Reporters",
    Standalone: false,
  },
  Inventor: {
    Places: ["Germany", "Illinois", "Italy", "Ohio", "United States"],
    PluralForm: "Inventors",
    Standalone: true,
  },
  Printmaker: {
    Places: ["Australia"],
    PluralForm: "Printmakers",
    Standalone: false,
  },
  "National Civil Servant": {
    Places: ["New Zealand"],
    PluralForm: "National Civil Servants",
    Standalone: true,
  },
  "Iron Worker": {
    Places: ["England"],
    PluralForm: "Iron Workers",
    Standalone: false,
  },
  "Lead Works Labourer": {
    Places: ["England"],
    PluralForm: "Lead Works Labourers",
    Standalone: false,
  },
  Clerk: {
    Places: ["England"],
    PluralForm: "Clerks",
    Standalone: true,
  },
  Clothier: {
    Places: ["England"],
    PluralForm: "Clothiers",
    Standalone: false,
  },
  "Agricultural Worker": {
    Places: ["England"],
    PluralForm: "Agricultural Workers",
    Standalone: true,
  },
  "Harness Maker": {
    Places: ["Australia", "England"],
    PluralForm: "Harness Makers",
    Standalone: true,
  },
  Tailor: {
    Places: ["Hungary", "Sweden"],
    PluralForm: "Tailors",
    Standalone: true,
  },
  Gardener: {
    Places: ["England"],
    PluralForm: "Gardeners",
    Standalone: true,
  },
  "Master Mariner": {
    Places: ["England"],
    PluralForm: "Master Mariners",
    Standalone: false,
  },
  "Colliery Lamp Cleaner": {
    Places: ["England"],
    PluralForm: "Colliery Lamp Cleaners",
    Standalone: false,
  },
  "Colliery Lashers-On": {
    Places: ["England"],
    PluralForm: "Colliery Lashers-On",
    Standalone: false,
  },
  Caterer: {
    Places: ["England"],
    PluralForm: "Caterers",
    Standalone: true,
  },
  "Law Enforcement": {
    Places: ["United States"],
    PluralForm: "Law Enforcement",
    Standalone: true,
  },
  Drover: {
    Places: ["Australia"],
    PluralForm: "Drovers",
    Standalone: true,
  },
  Aviator: {
    Places: ["Australia"],
    PluralForm: "Aviators",
    Standalone: true,
  },
  Distiller: {
    Places: ["Campbeltown, Argyll"],
    PluralForm: "Distillers",
    Standalone: true,
  },
  Stationer: {
    Places: ["Argyll", "Scotland"],
    PluralForm: "Stationers",
    Standalone: false,
  },
  Driver: {
    Places: ["England"],
    PluralForm: "Drivers",
    Standalone: true,
  },
  "US Postmaster": {
    Places: ["Arkansas"],
    PluralForm: "US Postmasters",
    Standalone: false,
  },
  "Laundry Manager": {
    Places: ["England"],
    PluralForm: "Laundry Manager",
    Standalone: false,
  },
  "Colliery Metal Contractor": {
    Places: ["England"],
    PluralForm: "Colliery Metal Contractors",
    Standalone: false,
  },
  "Commercial Traveller": {
    Places: ["Winnebago County, Illinois"],
    PluralForm: "Commercial Travellers",
    Standalone: false,
  },
  Cooper: {
    Places: ["Illinois"],
    PluralForm: "Coopers",
    Standalone: false,
  },
  "Hosiery Warehouseman": {
    Places: ["England"],
    PluralForm: "Hosiery Warehousemen",
    Standalone: false,
  },
  "Railway Worker": {
    Places: ["England"],
    PluralForm: "Railway Workers",
    Standalone: false,
  },
  "Munitions Worker": {
    Places: ["England"],
    PluralForm: "Munitions Workers",
    Standalone: false,
  },
  "Chimney Sweep": {
    Places: ["England"],
    PluralForm: "Chimney Sweeps",
    Standalone: true,
  },
  "Bible Woman": {
    Places: ["England"],
    PluralForm: "Bible Women",
    Standalone: true,
  },
  Brewer: {
    Places: ["England"],
    PluralForm: "Brewers",
    Standalone: true,
  },
  "Piano Tuner": {
    Places: ["England"],
    PluralForm: "Piano Tuners",
    Standalone: false,
  },
  "Dairy Maid": {
    Places: ["England"],
    PluralForm: "Dairy Maids",
    Standalone: false,
  },
  Miner: {
    Places: ["Australia", "England"],
    PluralForm: "Miners",
    Standalone: true,
  },
  "Professional Genealogist": {
    Places: [
      "Alabama",
      "Arizona",
      "Arkansas",
      "California",
      "Colorado",
      "Connecticut",
      "Delaware",
      "Florida",
      "Georgia",
      "Germany",
      "Idaho",
      "Illinois",
      "Indiana",
      "Kansas",
      "Kentucky",
      "Maine",
      "Michigan",
      "Nebraska",
      "New Hampshire",
      "New York",
      "Ohio",
      "Oregon",
      "South Dakota",
      "Tennessee",
      "Utah",
      "Washington",
      "Wisconsin",
    ],
    PluralForm: "Professional Genealogists",
    Standalone: false,
  },
  Model: {
    Places: ["Australia"],
    PluralForm: "Models",
    Standalone: true,
  },
  "Colliery Manager": {
    Places: ["England"],
    PluralForm: "Colliery Managers",
    Standalone: false,
  },
  "Glass Maker": {
    Places: ["England"],
    PluralForm: "Glass Makers",
    Standalone: false,
  },
  "Grocer\u0027s Assistant": {
    Places: ["England"],
    PluralForm: "Grocer\u0027s Assistants",
    Standalone: false,
  },
  Newsagent: {
    Places: ["England"],
    PluralForm: "Newsagents",
    Standalone: false,
  },
  "Glass Examiner": {
    Places: ["England"],
    PluralForm: "Glass Examiners",
    Standalone: false,
  },
  "Market Gardener": {
    Places: ["England"],
    PluralForm: "Market Gardeners",
    Standalone: true,
  },
  "Lace Bobbin Maker": {
    Places: ["England"],
    PluralForm: "Lace Bobbin Makers",
    Standalone: false,
  },
  Lexicographer: {
    Places: ["England"],
    PluralForm: "Lexicographers",
    Standalone: false,
  },
  Blacksmith: {
    Places: ["Argyll", "England", "Scotland"],
    PluralForm: "Blacksmiths",
    Standalone: true,
  },
  Squatter: {
    Places: ["Australia"],
    PluralForm: "Squatters",
    Standalone: false,
  },
  "Fly Driver": {
    Places: ["England"],
    PluralForm: "Fly Drivers",
    Standalone: false,
  },
  "Forestry Worker": {
    Places: ["Australia"],
    PluralForm: "Forestry Workers",
    Standalone: true,
  },
  "Wagon Maker": {
    Places: ["Argyll", "Scotland"],
    PluralForm: "Wagon Makers",
    Standalone: false,
  },
  Postman: {
    Places: ["England"],
    PluralForm: "Postmen",
    Standalone: false,
  },
  Milliner: {
    Places: ["England"],
    PluralForm: "Milliners",
    Standalone: false,
  },
  Geologist: {
    Places: ["Australia"],
    PluralForm: "Geologists",
    Standalone: false,
  },
  "Post Office Clerk": {
    Places: ["England"],
    PluralForm: "Post Office Clerks",
    Standalone: false,
  },
  "Laboratory Assistant": {
    Places: ["England"],
    PluralForm: "Laboratory Assistants",
    Standalone: false,
  },
  Mechanic: {
    Places: ["England"],
    PluralForm: "Mechanics",
    Standalone: true,
  },
  Industrialist: {
    Places: ["Alabama"],
    PluralForm: "Industrialists",
    Standalone: false,
  },
  Nurseryman: {
    Places: ["England"],
    PluralForm: "Nurserymen",
    Standalone: true,
  },
  Ballerina: {
    Places: ["Australia"],
    PluralForm: "Ballerinas",
    Standalone: true,
  },
  Broadcaster: {
    Places: ["Canada"],
    PluralForm: "Broadcasters",
    Standalone: true,
  },
  "Marine Engineer": {
    Places: ["England"],
    PluralForm: "Marine Engineers",
    Standalone: false,
  },
  Bricklayer: {
    Places: ["England"],
    PluralForm: "Bricklayers",
    Standalone: true,
  },
  Gastroenterologist: {
    Places: ["England"],
    PluralForm: "Gastroenterologists",
    Standalone: false,
  },
  Architect: {
    Places: ["Australia", "England", "New Zealand"],
    PluralForm: "Architects",
    Standalone: true,
  },
  Labourer: {
    Places: ["England"],
    PluralForm: "Labourers",
    Standalone: false,
  },
  "Printer\u0027s Assistant": {
    Places: ["England"],
    PluralForm: "Printer\u0027s Assistants",
    Standalone: false,
  },
  "Printer Compositor": {
    Places: ["England"],
    PluralForm: "Printer Compositors",
    Standalone: false,
  },
  Sportswoman: {
    Places: ["Sweden"],
    PluralForm: "Sportswomen",
    Standalone: false,
  },
  "Language Interpreter": {
    Places: ["England"],
    PluralForm: "Language Interpreters",
    Standalone: false,
  },
  "Quay Master": {
    Places: ["England"],
    PluralForm: "Quay Masters",
    Standalone: true,
  },
  Entrepreneur: {
    Places: ["Australia", "Florida", "Louisiana", "Michigan", "Pennsylvania", "Virginia"],
    PluralForm: "Entrepreneurs",
    Standalone: true,
  },
  "Justices Of The Peace": {
    Places: ["New Zealand"],
    PluralForm: "Justices of the Peace",
    Standalone: false,
  },
  Grounder: {
    Places: ["England"],
    PluralForm: "Grounders",
    Standalone: false,
  },
  "Truck Driver": {
    Places: ["Australia"],
    PluralForm: "Truck Drivers",
    Standalone: false,
  },
  Clergy: {
    Places: ["England"],
    PluralForm: "Clergy",
    Standalone: false,
  },
  "Office Holder": {
    Places: ["Australia", "Sweden"],
    PluralForm: "Office Holders",
    Standalone: true,
  },
  Banker: {
    Places: ["Australia", "California", "Illinois", "Indiana", "Pennsylvania", "Tennessee", "United States"],
    PluralForm: "Bankers",
    Standalone: true,
  },
  Footman: {
    Places: ["England"],
    PluralForm: "Footmen",
    Standalone: false,
  },
  "Munitions Fitter": {
    Places: ["England"],
    PluralForm: "Munitions Fitters",
    Standalone: false,
  },
  "Walking Stick Manufacturer": {
    Places: ["England"],
    PluralForm: "Walking Stick Manufacturers",
    Standalone: false,
  },
  Dressmaker: {
    Places: ["Argyll", "England", "Scotland", "United States", "Winnebago County, Illinois"],
    PluralForm: "Dressmakers",
    Standalone: true,
  },
  "Music Hall Artist": {
    Places: ["England"],
    PluralForm: "Music Hall Artists",
    Standalone: false,
  },
  "Hotel Proprietor": {
    Places: ["England"],
    PluralForm: "Hotel Proprietors",
    Standalone: false,
  },
  "Rag Dealer": {
    Places: ["England"],
    PluralForm: "Rag Dealers",
    Standalone: false,
  },
  Potter: {
    Places: ["Australia", "England"],
    PluralForm: "Potters",
    Standalone: true,
  },
  Publican: {
    Places: ["England"],
    PluralForm: "Publicans",
    Standalone: true,
  },
  "Black Beauty Shop Owner": {
    Places: ["United States of America"],
    PluralForm: "Black Beauty Shop Owners",
    Standalone: false,
  },
  "Great Lake": {
    Places: ["Sailor"],
    PluralForm: "Great Lakes",
    Standalone: false,
  },
  Chef: {
    Places: ["Australia"],
    PluralForm: "Chefs",
    Standalone: true,
  },
  Headmistresse: {
    Places: ["England"],
    PluralForm: "Headmistresses",
    Standalone: false,
  },
  Pierman: {
    Places: ["England"],
    PluralForm: "Piermen",
    Standalone: false,
  },
  "Powder Works Hand": {
    Places: ["England"],
    PluralForm: "Powder Works Hands",
    Standalone: false,
  },
  "Furniture Manufacturer": {
    Places: ["Winnebago County, Illinois"],
    PluralForm: "Furniture Manufacturers",
    Standalone: false,
  },
  "Knowledge Manager": {
    Places: ["Australia"],
    PluralForm: "Knowledge Managers",
    Standalone: true,
  },
  "Catholic Priest": {
    Places: ["Australia"],
    PluralForm: "Catholic Priests",
    Standalone: true,
  },
  "Real Estate Agent": {
    Places: ["Canada", "Winnebago County, Illinois"],
    PluralForm: "Real Estate Agents",
    Standalone: true,
  },
  "Building Contractor": {
    Places: ["Winnebago County, Illinois"],
    PluralForm: "Building Contractors",
    Standalone: true,
  },
  "Glass Blower": {
    Places: ["England"],
    PluralForm: "Glass Blowers",
    Standalone: false,
  },
  "Cow Keeper": {
    Places: ["England"],
    PluralForm: "Cow Keepers",
    Standalone: false,
  },
  "Barometer Maker": {
    Places: ["England"],
    PluralForm: "Barometer Makers",
    Standalone: true,
  },
  "Coach Builder": {
    Places: ["England"],
    PluralForm: "Coach Builders",
    Standalone: false,
  },
  "Ministers Of The Church": {
    Places: ["England"],
    PluralForm: "Ministers of the Church",
    Standalone: false,
  },
  Bookkeeper: {
    Places: ["England", "Winnebago County, Illinois"],
    PluralForm: "Bookkeepers",
    Standalone: true,
  },
  Maltster: {
    Places: ["England"],
    PluralForm: "Maltsters",
    Standalone: true,
  },
  Driller: {
    Places: ["England"],
    PluralForm: "Drillers",
    Standalone: false,
  },
  Entertainer: {
    Places: ["Australia", "Canada", "England", "France", "New Zealand", "United States"],
    PluralForm: "Entertainers",
    Standalone: false,
  },
  "Colliery Brakesman": {
    Places: ["England"],
    PluralForm: "Colliery Brakesmen",
    Standalone: false,
  },
  "Meal Merchant": {
    Places: ["England"],
    PluralForm: "Meal Merchants",
    Standalone: false,
  },
  Brushmaker: {
    Places: ["England"],
    PluralForm: "Brushmakers",
    Standalone: false,
  },
  Mariner: {
    Places: ["England"],
    PluralForm: "Mariners",
    Standalone: true,
  },
  "Rural Innkeeper": {
    Places: ["Sweden"],
    PluralForm: "Rural Innkeepers",
    Standalone: false,
  },
  "Paper Maker": {
    Places: ["England"],
    PluralForm: "Paper Makers",
    Standalone: false,
  },
  Fruiterer: {
    Places: ["England"],
    PluralForm: "Fruiterers",
    Standalone: false,
  },
  "Domestic Servant": {
    Places: ["England", "Winnebago County, Illinois"],
    PluralForm: "Domestic Servants",
    Standalone: false,
  },
  Laundress: {
    Places: ["England"],
    PluralForm: "Laundresses",
    Standalone: false,
  },
  "Hardware Merchant": {
    Places: ["England", "Winnebago County, Illinois"],
    PluralForm: "Hardware Merchants",
    Standalone: false,
  },
  Housekeeper: {
    Places: ["England"],
    PluralForm: "Housekeepers",
    Standalone: true,
  },
  "Alkali Labourer": {
    Places: ["England"],
    PluralForm: "Alkali Labourers",
    Standalone: false,
  },
  "Colliery Engineer": {
    Places: ["England"],
    PluralForm: "Colliery Engineers",
    Standalone: false,
  },
  Archivist: {
    Places: ["Australia"],
    PluralForm: "Archivists",
    Standalone: true,
  },
  Plumber: {
    Places: ["Australia", "England"],
    PluralForm: "Plumbers",
    Standalone: true,
  },
  Butler: {
    Places: ["England"],
    PluralForm: "Butlers",
    Standalone: true,
  },
  Sheriff: {
    Places: [
      "Alabama",
      "Arkansas",
      "California",
      "Colorado",
      "Iowa",
      "Iredell County, North Carolina",
      "Michigan",
      "Nebraska",
      "New York",
      "Ohio",
      "Pennsylvania",
      "Scotland",
      "Tennessee",
      "Texas",
    ],
    PluralForm: "Sheriffs",
    Standalone: true,
  },
  "Inland Revenue Collector": {
    Places: ["England"],
    PluralForm: "Inland Revenue Collectors",
    Standalone: true,
  },
  Barrister: {
    Places: ["Australia"],
    PluralForm: "Barristers",
    Standalone: true,
  },
  Cowman: {
    Places: ["England"],
    PluralForm: "Cowmen",
    Standalone: false,
  },
  Astronomer: {
    Places: ["Australia", "New Zealand"],
    PluralForm: "Astronomers",
    Standalone: true,
  },
  Greengrocer: {
    Places: ["England"],
    PluralForm: "Greengrocers",
    Standalone: true,
  },
  "Haulage Contractor": {
    Places: ["England"],
    PluralForm: "Haulage Contractors",
    Standalone: false,
  },
  "Pattern Maker": {
    Places: ["England"],
    PluralForm: "Pattern Makers",
    Standalone: true,
  },
  Historian: {
    Places: ["Australia", "France", "New Zealand", "Winnebago County, Illinois"],
    PluralForm: "Historians",
    Standalone: false,
  },
  Scientist: {
    Places: ["Australia", "Germany", "New Zealand"],
    PluralForm: "Scientists",
    Standalone: true,
  },
  Pastoralist: {
    Places: ["Australia"],
    PluralForm: "Pastoralists",
    Standalone: true,
  },
  "Boiler Maker": {
    Places: ["England"],
    PluralForm: "Boiler Makers",
    Standalone: false,
  },
  "Station Hand": {
    Places: ["Australia"],
    PluralForm: "Station Hands",
    Standalone: false,
  },
  "Colliery Metal Men": {
    Places: ["England"],
    PluralForm: "Colliery Metal Men",
    Standalone: false,
  },
  Illustrator: {
    Places: ["Australia"],
    PluralForm: "Illustrators",
    Standalone: false,
  },
  "Insurance Clerk": {
    Places: ["England"],
    PluralForm: "Insurance Clerks",
    Standalone: true,
  },
  Attorney: {
    Places: ["Florida", "Illinois", "Indiana", "Kentucky", "Pennsylvania"],
    PluralForm: "Attorneys",
    Standalone: true,
  },
  Innkeeper: {
    Places: ["Argyll", "England", "Scotland"],
    PluralForm: "Innkeepers",
    Standalone: true,
  },
  Agent: {
    Places: ["News"],
    PluralForm: "Agent",
    Standalone: false,
  },
  "Notable Writer": {
    Places: ["Canada"],
    PluralForm: "Notable Writers",
    Standalone: false,
  },
  Grocer: {
    Places: ["Argyll", "Australia", "England", "Scotland"],
    PluralForm: "Grocers",
    Standalone: true,
  },
  Coachman: {
    Places: ["England"],
    PluralForm: "Coachmen",
    Standalone: false,
  },
  "Motor Proprietor": {
    Places: ["England"],
    PluralForm: "Motor Proprietors",
    Standalone: false,
  },
  "Information Technology Manager": {
    Places: ["England"],
    PluralForm: "Information Technology Managers",
    Standalone: true,
  },
  Fisherman: {
    Places: ["Argyll", "Australia", "Scotland"],
    PluralForm: "Fishermen",
    Standalone: true,
  },
  Singer: {
    Places: ["Australia", "New Zealand"],
    PluralForm: "Singers",
    Standalone: false,
  },
  Vintner: {
    Places: ["Australia"],
    PluralForm: "Vintners",
    Standalone: true,
  },
  "Colliery Lamp Examiner": {
    Places: ["England"],
    PluralForm: "Colliery Lamp Examiners",
    Standalone: false,
  },
  "Bank Clerk": {
    Places: ["England"],
    PluralForm: "Bank Clerks",
    Standalone: true,
  },
  Ironmonger: {
    Places: ["Argyll", "England", "Scotland"],
    PluralForm: "Ironmongers",
    Standalone: false,
  },
  "Lighthouse Keeper": {
    Places: ["Argyll", "Scotland"],
    PluralForm: "Lighthouse Keepers",
    Standalone: true,
  },
  "Pipe Fitter": {
    Places: ["England"],
    PluralForm: "Pipe Fitters",
    Standalone: false,
  },
  Painter: {
    Places: ["Australia", "England", "New Zealand"],
    PluralForm: "Painters",
    Standalone: false,
  },
  "Gate Keeper": {
    Places: ["England"],
    PluralForm: "Gate Keepers",
    Standalone: false,
  },
  Barmaid: {
    Places: ["England"],
    PluralForm: "Barmaids",
    Standalone: true,
  },
  Clergyman: {
    Places: ["England"],
    PluralForm: "Clergymen",
    Standalone: false,
  },
  Builder: {
    Places: ["Australia", "England"],
    PluralForm: "Builders",
    Standalone: true,
  },
  Firefighter: {
    Places: [
      "Alabama",
      "California",
      "Connecticut",
      "Illinois",
      "Indiana",
      "Louisiana",
      "Maine",
      "New Hampshire",
      "New York",
      "Ohio",
      "Pennsylvania",
      "Wisconsin",
    ],
    PluralForm: "Firefighters",
    Standalone: true,
  },
  "Ballad Writer": {
    Places: ["Australia"],
    PluralForm: "Ballad Writers",
    Standalone: false,
  },
  Author: {
    Places: ["Alabama", "Australia", "Canada", "New Zealand", "Puerto Rico", "Scotland", "Sweden"],
    PluralForm: "Authors",
    Standalone: true,
  },
  "Story-Teller": {
    Places: ["Traditional Singer-Songwriter"],
    PluralForm: "Story-teller",
    Standalone: false,
  },
  "Public Servant": {
    Places: ["Australia"],
    PluralForm: "Public Servants",
    Standalone: false,
  },
  "Newspaper Publisher": {
    Places: ["Illinois"],
    PluralForm: "Newspaper Publishers",
    Standalone: false,
  },
  Mayor: {
    Places: ["New Zealand"],
    PluralForm: "Mayors",
    Standalone: false,
  },
  Plasterer: {
    Places: ["England"],
    PluralForm: "Plasterers",
    Standalone: false,
  },
  Company: {
    Places: ["Scotland"],
    PluralForm: "Companies",
    Standalone: false,
  },
  Engineer: {
    Places: ["Australia", "England", "New Zealand"],
    PluralForm: "Engineers",
    Standalone: true,
  },
  Organist: {
    Places: ["England"],
    PluralForm: "Organists",
    Standalone: false,
  },
  "Paper Hanger": {
    Places: ["England"],
    PluralForm: "Paper Hangers",
    Standalone: false,
  },
  "House Decorator": {
    Places: ["England"],
    PluralForm: "House Decorators",
    Standalone: false,
  },
  "Leather Dresser": {
    Places: ["England"],
    PluralForm: "Leather Dressers",
    Standalone: false,
  },
  Nurse: {
    Places: ["Australia", "Canada", "England"],
    PluralForm: "Nurses",
    Standalone: true,
  },
  "Colliery Checkweighman": {
    Places: ["England"],
    PluralForm: "Colliery Checkweighmen",
    Standalone: false,
  },
  Confectioner: {
    Places: ["Australia", "England"],
    PluralForm: "Confectioners",
    Standalone: true,
  },
  "House Agent": {
    Places: ["England"],
    PluralForm: "House Agents",
    Standalone: false,
  },
  Coroner: {
    Places: ["Canada", "England"],
    PluralForm: "Coroners",
    Standalone: true,
  },
  "Motor Mechanic": {
    Places: ["Australia"],
    PluralForm: "Motor Mechanics",
    Standalone: false,
  },
  Police: {
    Places: ["Canada", "England"],
    PluralForm: "Police",
    Standalone: false,
  },
  Gamekeeper: {
    Places: ["Argyll", "Scotland"],
    PluralForm: "Gamekeepers",
    Standalone: true,
  },
  "Colliery Weighman": {
    Places: ["England"],
    PluralForm: "Colliery Weighmen",
    Standalone: false,
  },
  "Colliery Contractor": {
    Places: ["England"],
    PluralForm: "Colliery Contractors",
    Standalone: false,
  },
  Diplomat: {
    Places: ["Australia", "New Zealand"],
    PluralForm: "Diplomats",
    Standalone: false,
  },
  Judge: {
    Places: [
      "Australia",
      "Colorado",
      "Connecticut",
      "Georgia",
      "Hungary",
      "Illinois",
      "Louisiana",
      "Michigan",
      "Missouri",
      "Nebraska",
      "New Mexico",
      "New York",
      "New Zealand",
      "Ohio",
      "Pennsylvania",
      "United States of America",
      "Utah",
    ],
    PluralForm: "Judges",
    Standalone: true,
  },
  "Brickyard Foreman": {
    Places: ["England"],
    PluralForm: "Brickyard Foremen",
    Standalone: false,
  },
  Midwive: {
    Places: ["Australia", "England"],
    PluralForm: "Midwives",
    Standalone: true,
  },
  "Metal Turner": {
    Places: ["England"],
    PluralForm: "Metal Turners",
    Standalone: false,
  },
  "Colliery Engine Driver": {
    Places: ["England"],
    PluralForm: "Colliery Engine Drivers",
    Standalone: false,
  },
  "Business Figure": {
    Places: ["Hungary"],
    PluralForm: "Business Figures",
    Standalone: false,
  },
  Bookseller: {
    Places: ["England"],
    PluralForm: "Booksellers",
    Standalone: true,
  },
  Carpenter: {
    Places: ["Australia", "England", "New Zealand", "Winnebago County, Illinois"],
    PluralForm: "Carpenters",
    Standalone: true,
  },
  "Colliery Sinker": {
    Places: ["England"],
    PluralForm: "Colliery Sinkers",
    Standalone: false,
  },
  "Marine Store Dealer": {
    Places: ["England"],
    PluralForm: "Marine Store Dealers",
    Standalone: false,
  },
  "Lady\u0027s Maid": {
    Places: ["England"],
    PluralForm: "Lady\u0027s Maids",
    Standalone: false,
  },
  Athlete: {
    Places: ["Canada"],
    PluralForm: "Athletes",
    Standalone: true,
  },
  Draper: {
    Places: ["Argyll", "England", "Scotland"],
    PluralForm: "Drapers",
    Standalone: true,
  },
  Solicitor: {
    Places: ["Australia"],
    PluralForm: "Solicitors",
    Standalone: false,
  },
  "Milk Vendor": {
    Places: ["Australia"],
    PluralForm: "Milk Vendors",
    Standalone: false,
  },
  "Glass Worker": {
    Places: ["England"],
    PluralForm: "Glass Workers",
    Standalone: true,
  },
  Hatter: {
    Places: ["England"],
    PluralForm: "Hatters",
    Standalone: false,
  },
  "New Zealand": {
    Places: ["Resident Magistrates"],
    PluralForm: "New Zealand",
    Standalone: true,
  },
  Sportsman: {
    Places: ["Sweden"],
    PluralForm: "Sportsmen",
    Standalone: false,
  },
  Showman: {
    Places: ["Australia"],
    PluralForm: "Showmen",
    Standalone: true,
  },
  "Members Of Parliament": {
    Places: ["New Zealand"],
    PluralForm: "Members of Parliament",
    Standalone: false,
  },
  "Candle Maker": {
    Places: ["England"],
    PluralForm: "Candle Makers",
    Standalone: true,
  },
  "Mill Machine Oil Setter": {
    Places: ["England"],
    PluralForm: "Mill Machine Oil Setters",
    Standalone: false,
  },
  "Jack Frame Tenter": {
    Places: ["England"],
    PluralForm: "Jack Frame Tenters",
    Standalone: false,
  },
  Photographer: {
    Places: ["Australia", "England", "Sweden"],
    PluralForm: "Photographers",
    Standalone: false,
  },
  Postmaster: {
    Places: ["Australia", "England", "Illinois", "Iredell County, North Carolina"],
    PluralForm: "Postmasters",
    Standalone: false,
  },
  "College And University Professor": {
    Places: ["United States"],
    PluralForm: "College and University Professors",
    Standalone: false,
  },
  "Cotton Weaver": {
    Places: ["England"],
    PluralForm: "Cotton Weavers",
    Standalone: true,
  },
  Politician: {
    Places: [
      "Alabama",
      "Alaska",
      "Arkansas",
      "Australia",
      "Florida",
      "Germany",
      "Illinois",
      "Iredell County, North Carolina",
      "New Zealand",
      "Oregon",
      "Wisconsin",
    ],
    PluralForm: "Politicians",
    Standalone: true,
  },
  Lawyer: {
    Places: ["England", "New Zealand", "Tennessee"],
    PluralForm: "Lawyers",
    Standalone: true,
  },
  Draughtsman: {
    Places: ["Australia"],
    PluralForm: "Draughtsmen",
    Standalone: false,
  },
  "Coal Miner": {
    Places: ["Alabama", "England", "Iowa", "Missouri", "New Mexico", "Sweden", "Washington"],
    PluralForm: "Coal Miners",
    Standalone: false,
  },
  "Religious Figure": {
    Places: ["Australia", "Canada", "England"],
    PluralForm: "Religious Figures",
    Standalone: false,
  },
  "Metal Tester": {
    Places: ["England"],
    PluralForm: "Metal Testers",
    Standalone: false,
  },
  "Coal Mine Labourer": {
    Places: ["England"],
    PluralForm: "Coal Mine Labourers",
    Standalone: false,
  },
  "Lodging House Keeper": {
    Places: ["England"],
    PluralForm: "Lodging House Keepers",
    Standalone: false,
  },
  "Licensed Victualler": {
    Places: ["England"],
    PluralForm: "Licensed Victuallers",
    Standalone: false,
  },
  "Police Officer": {
    Places: ["Australia", "Illinois", "Indiana", "New Zealand"],
    PluralForm: "Police Officers",
    Standalone: true,
  },
  "Grocer\u0027s Warehouseman": {
    Places: ["England"],
    PluralForm: "Grocer\u0027s Warehousemen",
    Standalone: false,
  },
  Cabinetmaker: {
    Places: ["Winnebago County, Illinois"],
    PluralForm: "Cabinetmakers",
    Standalone: true,
  },
  Surgeon: {
    Places: ["New Zealand"],
    PluralForm: "Surgeons",
    Standalone: true,
  },
  "Jam Maker": {
    Places: ["England"],
    PluralForm: "Jam Makers",
    Standalone: false,
  },
  Teacher: {
    Places: [
      "Arizona",
      "California",
      "Canada",
      "Georgia",
      "Germany",
      "Iowa",
      "Kentucky",
      "Michigan",
      "New Mexico",
      "New York",
      "Ohio",
      "Tennessee",
      "Texas",
      "Winnebago County, Illinois",
      "Wisconsin",
    ],
    PluralForm: "Teachers",
    Standalone: false,
  },
  "Glass Polisher": {
    Places: ["England"],
    PluralForm: "Glass Polishers",
    Standalone: false,
  },
  Dentist: {
    Places: ["Australia"],
    PluralForm: "Dentists",
    Standalone: true,
  },
  "Mining Contractor": {
    Places: ["England"],
    PluralForm: "Mining Contractors",
    Standalone: true,
  },
  "Chief Constable": {
    Places: ["England"],
    PluralForm: "Chief Constables",
    Standalone: true,
  },
  "Black Laundresse": {
    Places: ["United States of America"],
    PluralForm: "Black Laundresses",
    Standalone: false,
  },
  Porter: {
    Places: ["England"],
    PluralForm: "Porters",
    Standalone: true,
  },
  Cook: {
    Places: ["England"],
    PluralForm: "Cooks",
    Standalone: true,
  },
  Headmaster: {
    Places: ["England"],
    PluralForm: "Headmasters",
    Standalone: false,
  },
  Farrier: {
    Places: ["California", "England"],
    PluralForm: "Farriers",
    Standalone: false,
  },
  "Lumber Miller": {
    Places: ["California"],
    PluralForm: "Lumber Millers",
    Standalone: false,
  },
  "Lace Manufacturer": {
    Places: ["England"],
    PluralForm: "Lace Manufacturers",
    Standalone: false,
  },
  Bootmaker: {
    Places: ["England"],
    PluralForm: "Bootmakers",
    Standalone: true,
  },
  Plater: {
    Places: ["England"],
    PluralForm: "Platers",
    Standalone: false,
  },
  Groom: {
    Places: ["England"],
    PluralForm: "Grooms",
    Standalone: false,
  },
  Doctor: {
    Places: ["Australia", "England"],
    PluralForm: "Doctors",
    Standalone: true,
  },
  Millwright: {
    Places: ["England"],
    PluralForm: "Millwrights",
    Standalone: true,
  },
  Shearer: {
    Places: ["Australia"],
    PluralForm: "Shearers",
    Standalone: false,
  },
  Journalist: {
    Places: ["Australia", "England", "Illinois", "Louisiana", "New Zealand", "Puerto Rico", "United States"],
    PluralForm: "Journalists",
    Standalone: true,
  },
  "Leather Works Manager": {
    Places: ["England"],
    PluralForm: "Leather Works Managers",
    Standalone: false,
  },
  Cricketer: {
    Places: ["New Zealand"],
    PluralForm: "Cricketers",
    Standalone: false,
  },
  Designer: {
    Places: ["England"],
    PluralForm: "Designers",
    Standalone: true,
  },
  Educator: {
    Places: ["Australia"],
    PluralForm: "Educators",
    Standalone: true,
  },
  Nanny: {
    Places: ["England"],
    PluralForm: "Nannies",
    Standalone: false,
  },
  Printer: {
    Places: ["England"],
    PluralForm: "Printers",
    Standalone: true,
  },
  Locksmith: {
    Places: ["England"],
    PluralForm: "Locksmiths",
    Standalone: true,
  },
  Baker: {
    Places: ["Argyll", "Australia", "England", "Scotland"],
    PluralForm: "Bakers",
    Standalone: true,
  },
  Writer: {
    Places: ["New Zealand"],
    PluralForm: "Writers",
    Standalone: true,
  },
  "Racing Car Driver": {
    Places: ["Australia", "New Zealand"],
    PluralForm: "Racing Car Drivers",
    Standalone: true,
  },
  Artist: {
    Places: ["Australia", "Canada", "New Zealand", "United States"],
    PluralForm: "Artists",
    Standalone: true,
  },
  "Black Barber": {
    Places: ["United States of America"],
    PluralForm: "Black Barbers",
    Standalone: false,
  },
  "Mechanical Engineer": {
    Places: ["England"],
    PluralForm: "Mechanical Engineers",
    Standalone: false,
  },
  Decorator: {
    Places: ["England"],
    PluralForm: "Decorators",
    Standalone: false,
  },
  Gilder: {
    Places: ["England"],
    PluralForm: "Gilders",
    Standalone: false,
  },
  Poet: {
    Places: ["Australia", "Puerto Rico"],
    PluralForm: "Poets",
    Standalone: false,
  },
  Cobbler: {
    Places: ["England"],
    PluralForm: "Cobblers",
    Standalone: true,
  },
  "Black Beautician": {
    Places: ["United States of America"],
    PluralForm: "Black Beauticians",
    Standalone: false,
  },
  Butcher: {
    Places: ["Australia", "England", "Winnebago County, Illinois"],
    PluralForm: "Butchers",
    Standalone: true,
  },
  "Gold Miner": {
    Places: ["California", "England"],
    PluralForm: "Gold Miners",
    Standalone: false,
  },
  "Pianoforte Maker": {
    Places: ["England"],
    PluralForm: "Pianoforte Makers",
    Standalone: false,
  },
  Farmer: {
    Places: ["Australia", "California", "Connecticut", "Delaware", "England"],
    PluralForm: "Farmers",
    Standalone: true,
  },
  "Painter And Decorator": {
    Places: ["England"],
    PluralForm: "Painter and Decorators",
    Standalone: false,
  },
  Glover: {
    Places: ["England"],
    PluralForm: "Glovers",
    Standalone: true,
  },
  "Boarding House Keeper": {
    Places: ["England"],
    PluralForm: "Boarding House Keepers",
    Standalone: false,
  },
  Machinist: {
    Places: ["England"],
    PluralForm: "Machinists",
    Standalone: true,
  },
  Moulder: {
    Places: ["Winnebago County"],
    PluralForm: "Moulders",
    Standalone: true,
  },
  Sculptor: {
    Places: ["Australia"],
    PluralForm: "Sculptors",
    Standalone: false,
  },
  Carrier: {
    Places: ["England"],
    PluralForm: "Carriers",
    Standalone: false,
  },
  Geographer: {
    Places: ["France"],
    PluralForm: "Geographers",
    Standalone: false,
  },
  Conjuror: {
    Places: ["England"],
    PluralForm: "Conjurors",
    Standalone: false,
  },
  Merchant: {
    Places: ["Australia", "England"],
    PluralForm: "Merchants",
    Standalone: true,
  },
  Physician: {
    Places: [
      "Alabama",
      "Alaska",
      "Arizona",
      "Arkansas",
      "California",
      "Canada",
      "Colorado",
      "Connecticut",
      "Delaware",
      "Florida",
      "Georgia",
      "Hawaii",
      "Idaho",
      "Illinois",
      "Indiana",
      "Iowa",
      "Kansas",
      "Kentucky",
      "Louisiana",
      "Maine",
      "Maryland",
      "Massachusetts",
      "Michigan",
      "Mississippi",
      "Missouri",
      "Montana",
      "Nebraska",
      "Nevada",
      "New Hampshire",
      "New Jersey",
      "New Mexico",
      "New York",
      "North Carolina",
      "North Dakota",
      "Ohio",
      "Oklahoma",
      "Oregon",
      "Pennsylvania",
      "Rhode Island",
      "South Carolina",
      "South Dakota",
      "Tennessee",
      "Texas",
      "United States",
      "Utah",
      "Vermont",
      "Virginia",
      "Washington",
      "West Virginia",
      "Winnebago County, Illinois",
      "Wisconsin",
      "Wyoming",
    ],
    PluralForm: "Physicians",
    Standalone: true,
  },
  Jeweller: {
    Places: ["England"],
    PluralForm: "Jewellers",
    Standalone: true,
  },
  Ostler: {
    Places: ["England"],
    PluralForm: "Ostlers",
    Standalone: false,
  },
  "Newspaper Proprietor": {
    Places: ["Australia"],
    PluralForm: "Newspaper Proprietors",
    Standalone: true,
  },
  Salespeople: {
    Places: ["Winnebago County, Illinois"],
    PluralForm: "Salespeople",
    Standalone: false,
  },
  Sawyer: {
    Places: ["Australia"],
    PluralForm: "Sawyers",
    Standalone: false,
  },
  Vigneron: {
    Places: ["Australia"],
    PluralForm: "Vignerons",
    Standalone: false,
  },
  "Drill Instructor": {
    Places: ["England"],
    PluralForm: "Drill Instructors",
    Standalone: true,
  },
  Carter: {
    Places: ["Argyll", "Australia", "England", "Scotland"],
    PluralForm: "Carters",
    Standalone: true,
  },
  "Mail Carrier": {
    Places: ["Winnebago County, Illinois"],
    PluralForm: "Mail Carriers",
    Standalone: false,
  },
  Horticulturalist: {
    Places: ["Alberta"],
    PluralForm: "Horticulturalists",
    Standalone: true,
  },
  Stenographer: {
    Places: ["Winnebago County, Illinois"],
    PluralForm: "Stenographers",
    Standalone: true,
  },
  Joiner: {
    Places: ["England"],
    PluralForm: "Joiners",
    Standalone: false,
  },
  Publisher: {
    Places: ["England"],
    PluralForm: "Publishers",
    Standalone: true,
  },
  Genealogist: {
    Places: ["England", "Germany", "United States"],
    PluralForm: "Genealogists",
    Standalone: false,
  },
  Surveyor: {
    Places: ["New Zealand", "Western Australia"],
    PluralForm: "Surveyors",
    Standalone: true,
  },
  Miller: {
    Places: ["England", "Winnebago County, Illinois"],
    PluralForm: "Millers",
    Standalone: true,
  },
  "Business Owner": {
    Places: ["Australia"],
    PluralForm: "Business Owners",
    Standalone: true,
  },
  "Omnibus Proprietor": {
    Places: ["England"],
    PluralForm: "Omnibus Proprietors",
    Standalone: false,
  },
  "Motor Manufacturer": {
    Places: ["England"],
    PluralForm: "Motor Manufacturers",
    Standalone: false,
  },
  Cellarman: {
    Places: ["England"],
    PluralForm: "Cellarmen",
    Standalone: true,
  },
  Milkman: {
    Places: ["England"],
    PluralForm: "Milkmen",
    Standalone: true,
  },
  "Rural Entrepreneur": {
    Places: ["Sicily"],
    PluralForm: "Rural Entrepreneurs",
    Standalone: false,
  },
  Librarian: {
    Places: ["Australia", "Canada", "England", "Winnebago County, Illinois"],
    PluralForm: "Librarians",
    Standalone: true,
  },
  "Coal Merchant": {
    Places: ["England"],
    PluralForm: "Coal Merchants",
    Standalone: true,
  },
  Musician: {
    Places: ["Alabama", "Australia", "England", "New Zealand", "Sweden"],
    PluralForm: "Musicians",
    Standalone: true,
  },
  Principal: {
    Places: ["California", "England"],
    PluralForm: "Principals",
    Standalone: false,
  },
  "Engine Driver": {
    Places: ["England"],
    PluralForm: "Engine Drivers",
    Standalone: false,
  },
  "Coach Painter": {
    Places: ["England"],
    PluralForm: "Coach Painters",
    Standalone: false,
  },
  Actor: {
    Places: ["Australia", "New Zealand", "Sweden"],
    PluralForm: "Actors",
    Standalone: true,
  },
  Pharmacist: {
    Places: ["England"],
    PluralForm: "Pharmacists",
    Standalone: true,
  },
  "Iron Moulder": {
    Places: ["Argyll", "Scotland"],
    PluralForm: "Iron Moulders",
    Standalone: false,
  },
  Cartoonist: {
    Places: ["Australia"],
    PluralForm: "Cartoonists",
    Standalone: true,
  },
  "Assistant Chemist": {
    Places: ["England"],
    PluralForm: "Assistant Chemists",
    Standalone: false,
  },
  "Cabinet Maker": {
    Places: ["England"],
    PluralForm: "Cabinet Makers",
    Standalone: false,
  },
  Compositor: {
    Places: ["England"],
    PluralForm: "Compositors",
    Standalone: false,
  },
  "Bottle Gauger": {
    Places: ["England"],
    PluralForm: "Bottle Gaugers",
    Standalone: true,
  },
  "Parish Clerk": {
    Places: ["England"],
    PluralForm: "Parish Clerks",
    Standalone: false,
  },
  "Hosiery Manufacturer": {
    Places: ["England"],
    PluralForm: "Hosiery Manufacturers",
    Standalone: false,
  },
  "Biscuit Maker": {
    Places: ["Australia"],
    PluralForm: "Biscuit Makers",
    Standalone: false,
  },
};
