export const unsourcedCategories = {
  Aargau: "Aargau,_Unsourced_Profiles",
  Aberdeenshire: "Aberdeenshire,_Unsourced_Profiles",
  Acadian: "Acadian,_Unsourced,_Source_Research_Done",
  Afghanistan: "Afghanistan,_Unsourced_Profiles",
  Africa: "Africa,_Unsourced_Profiles",
  Aguascalientes: "Aguascalientes,_Unsourced_Profiles",
  Ain: "Ain,_Unsourced_Profiles",
  Aisne: "Aisne,_Unsourced_Profiles",
  Alabama: "Alabama,_Unsourced_Profiles",
  Alaska: "Alaska,_Unsourced_Profiles",
  Alberta: "Alberta,_Unsourced_Profiles",
  Algeria: "Algeria,_Unsourced_Profiles",
  Allier: "Allier,_Unsourced_Profiles",
  "Alpes-Maritimes": "Alpes-Maritimes,_Unsourced_Profiles",
  "Alpes-de-Haute-Provence": "Alpes-de-Haute-Provence,_Unsourced_Profiles",
  "American Samoa": "American_Samoa,_Unsourced_Profiles",
  Andalusia: "Andalusia,_Unsourced_Profiles",
  Andorra: "Andorra,_Unsourced_Profiles",
  Anglesey: "Anglesey,_Unsourced_Profiles",
  Angola: "Angola,_Unsourced_Profiles",
  Angus: "Angus,_Unsourced_Profiles",
  "Antigua and Barbuda": "Antigua_and_Barbuda,_Unsourced_Profiles",
  Appalachia: "Appalachia,_Unsourced_Profiles",
  Ardennes: "Ardennes,_Unsourced_Profiles",
  Ardèche: "Ardèche,_Unsourced_Profiles",
  Argentina: "Argentina,_Unsourced_Profiles",
  Argyll: "Argyll,_Unsourced_Profiles",
  Arizona: "Arizona,_Unsourced_Profiles",
  Ariège: "Ariège,_Unsourced_Profiles",
  Arkansas: "Arkansas,_Unsourced_Profiles",
  Armenia: "Armenia,_Unsourced_Profiles",
  Asia: "Asia,_Unsourced_Profiles",
  Aube: "Aube,_Unsourced_Profiles",
  Aude: "Aude,_Unsourced_Profiles",
  Austria: "Austria,_Unsourced_Profiles",
  Aveyron: "Aveyron,_Unsourced_Profiles",
  Ayrshire: "Ayrshire,_Unsourced_Profiles",
  Azerbaijan: "Azerbaijan,_Unsourced_Profiles",
  Baden: "Baden,_Unsourced_Profiles",
  "Baden-Württemberg": "Baden-Württemberg,_Unsourced_Profiles",
  Bahamas: "The_Bahamas,_Unsourced_Profiles",
  Banffshire: "Banffshire,_Unsourced_Profiles",
  Bangladesh: "Bangladesh,_Unsourced_Profiles",
  Barbados: "Barbados,_Unsourced_Profiles",
  "Bas-Rhin": "Bas-Rhin,_Unsourced_Profiles",
  Bavaria: "Bavaria,_Unsourced_Profiles",
  Bayern: "Bayern,_Unsourced_Profiles",
  Bedfordshire: "Bedfordshire,_Unsourced_Profiles",
  Belarus: "Belarus,_Unsourced_Profiles",
  "Belfast City": "Belfast_City,_Unsourced_Profiles",
  Belgium: "Belgium,_Unsourced_Profiles",
  Belize: "Belize,_Unsourced_Profiles",
  Berkshire: "Berkshire,_Unsourced_Profiles",
  Berlin: "Berlin,_Unsourced_Profiles",
  Bermuda: "Bermuda,_Unsourced_Profiles",
  Berwickshire: "Berwickshire,_Unsourced_Profiles",
  Bohemia: "Bohemia,_Unsourced_Profiles",
  Bolivia: "Bolivia,_Unsourced_Profiles",
  Botswana: "Botswana,_Unsourced_Profiles",
  "Bouches-du-Rhône": "Bouches-du-Rhône,_Unsourced_Profiles",
  Brandenburg: "Brandenburg,_Unsourced_Profiles",
  Brazil: "Brazil,_Unsourced_Profiles",
  Brecknockshire: "Brecknockshire,_Unsourced_Profiles",
  Bremen: "Bremen,_Unsourced_Profiles",
  Bristol: "Bristol,_Unsourced_Profiles",
  "British Columbia": "British_Columbia,_Unsourced_Profiles",
  Brunei: "Brunei,_Unsourced_Profiles",
  Brunson: "Brunson,_Unsourced_Profiles",
  Buckfastleigh: "Buckfastleigh,_Devon_One_Place_Study_Unsourced",
  Buckinghamshire: "Buckinghamshire,_Unsourced_Profiles",
  Bulgaria: "Bulgaria,_Unsourced_Profiles",
  "Burkina Faso": "Burkina_Faso,_Unsourced_Profiles",
  Burma: "Burma,_Unsourced_Profiles",
  Bute: "Bute,_Unsourced_Profiles",
  Caernarfonshire: "Caernarfonshire,_Unsourced_Profiles",
  Caithness: "Caithness,_Unsourced_Profiles",
  California: "California,_Unsourced_Profiles",
  Calvados: "Calvados,_Unsourced_Profiles",
  Cambridgeshire: "Cambridgeshire,_Unsourced_Profiles",
  Cameroon: "Cameroon,_Unsourced_Profiles",
  Canada: "Canada,_Unsourced_Profiles",
  "Canary Islands": "Canary_Islands,_Unsourced_Profiles",
  Cantal: "Cantal,_Unsourced_Profiles",
  "Canton of Aargau": "Canton_of_Aargau,_Unsourced_Profiles",
  "Canton of Appenzell Ausserrhoden": "Canton_of_Appenzell_Ausserrhoden,_Unsourced_Profiles",
  "Canton of Appenzell Innerrhoden": "Canton_of_Appenzell_Innerrhoden,_Unsourced_Profiles",
  "Canton of Basel-Landschaft": "Canton_of_Basel-Landschaft,_Unsourced_Profiles",
  "Canton of Basel-Stadt": "Canton_of_Basel-Stadt,_Unsourced_Profiles",
  "Canton of Bern": "Canton_of_Bern,_Unsourced_Profiles",
  "Canton of Geneva": "Canton_of_Geneva,_Unsourced_Profiles",
  "Canton of Glarus": "Canton_of_Glarus,_Unsourced_Profiles",
  "Canton of Grisons": "Canton_of_Grisons,_Unsourced_Profiles",
  "Canton of Neuchâtel": "Canton_of_Neuchâtel,_Unsourced_Profiles",
  "Canton of Schaffhausen": "Canton_of_Schaffhausen,_Unsourced_Profiles",
  "Canton of Solothurn": "Canton_of_Solothurn,_Unsourced_Profiles",
  "Canton of St. Gallen": "Canton_of_St._Gallen,_Unsourced_Profiles",
  "Canton of Thurgau": "Canton_of_Thurgau,_Unsourced_Profiles",
  "Canton of Valais": "Canton_of_Valais,_Unsourced_Profiles",
  "Canton of Vaud": "Canton_of_Vaud,_Unsourced_Profiles",
  "Canton of Zürich": "Canton_of_Zürich,_Unsourced_Profiles",
  "Cape Colony": "Cape_Colony,_Unsourced_Profiles",
  "Cape Province": "Cape_Province,_Unsourced_Profiles",
  Cardiganshire: "Cardiganshire,_Unsourced_Profiles",
  Caribbean: "Caribbean,_Unsourced_Profiles",
  Carmarthenshire: "Carmarthenshire,_Unsourced_Profiles",
  Catalonia: "Catalonia,_Unsourced_Profiles",
  "Central America": "Central_America,_Unsourced_Profiles",
  "Channel Islands": "Channel_Islands,_Unsourced_Profiles",
  Charente: "Charente,_Unsourced_Profiles",
  "Charente-Maritime": "Charente-Maritime,_Unsourced_Profiles",
  Cher: "Cher,_Unsourced_Profiles",
  Cheshire: "Cheshire,_Unsourced_Profiles",
  Chihuahua: "Chihuahua,_Unsourced_Profiles",
  Chile: "Chile,_Unsourced_Profiles",
  China: "China,_Unsourced_Profiles",
  Clackmannanshire: "Clackmannanshire,_Unsourced_Profiles",
  Colombia: "Colombia,_Unsourced_Profiles",
  Colorado: "Colorado,_Unsourced_Profiles",
  Connecticut: "Connecticut,_Unsourced_Profiles",
  "Cook Islands": "Cook_Islands,_Unsourced_Profiles",
  Cornwall: "Cornwall,_Unsourced_Profiles",
  Corrèze: "Corrèze,_Unsourced_Profiles",
  "Corse-du-Sud": "Corse-du-Sud,_Unsourced_Profiles",
  Corsica: "Corsica,_Unsourced_Profiles",
  "Costa Rica": "Costa_Rica,_Unsourced_Profiles",
  "County Antrim": "County_Antrim,_Unsourced_Profiles",
  "County Armagh": "County_Armagh,_Unsourced_Profiles",
  "County Carlow": "County_Carlow,_Unsourced_Profiles",
  "County Cavan": "County_Cavan,_Unsourced_Profiles",
  "County Clare": "County_Clare,_Unsourced_Profiles",
  "County Cork": "County_Cork,_Unsourced_Profiles",
  "County Donegal": "County_Donegal,_Unsourced_Profiles",
  "County Down": "County_Down,_Unsourced_Profiles",
  "County Dublin": "County_Dublin,_Unsourced_Profiles",
  "County Durham": "County_Durham,_Unsourced_Profiles",
  "County Fermanagh": "County_Fermanagh,_Unsourced_Profiles",
  "County Galway": "County_Galway,_Unsourced_Profiles",
  "County Kerry": "County_Kerry,_Unsourced_Profiles",
  "County Kildare": "County_Kildare,_Unsourced_Profiles",
  "County Kilkenny": "County_Kilkenny,_Unsourced_Profiles",
  "County Laois": "County_Laois,_Unsourced_Profiles",
  "County Leitrim": "County_Leitrim,_Unsourced_Profiles",
  "County Limerick": "County_Limerick,_Unsourced_Profiles",
  "County Londonderry": "County_Londonderry,_Unsourced_Profiles",
  "County Longford": "County_Longford,_Unsourced_Profiles",
  "County Louth": "County_Louth,_Unsourced_Profiles",
  "County Mayo": "County_Mayo,_Unsourced_Profiles",
  "County Meath": "County_Meath,_Unsourced_Profiles",
  "County Monaghan": "County_Monaghan,_Unsourced_Profiles",
  "County Offaly": "County_Offaly,_Unsourced_Profiles",
  "County Roscommon": "County_Roscommon,_Unsourced_Profiles",
  "County Sligo": "County_Sligo,_Unsourced_Profiles",
  "County Tipperary": "County_Tipperary,_Unsourced_Profiles",
  "County Tyrone": "County_Tyrone,_Unsourced_Profiles",
  "County Waterford": "County_Waterford,_Unsourced_Profiles",
  "County Westmeath": "County_Westmeath,_Unsourced_Profiles",
  "County Wexford": "County_Wexford,_Unsourced_Profiles",
  "County Wicklow": "County_Wicklow,_Unsourced_Profiles",
  Creuse: "Creuse,_Unsourced_Profiles",
  Croatia: "Croatia,_Unsourced_Profiles",
  Cuba: "Cuba,_Unsourced_Profiles",
  "Cudmore Name Study": "Cudmore_Name_Study,_Unsourced_Profiles",
  Cumberland: "Cumberland,_Unsourced_Profiles",
  Curaçao: "Curaçao,_Unsourced_Profiles",
  "Czech Republic": "Czech_Republic,_Unsourced_Profiles",
  Czechoslovakia: "Czechoslovakia,_Unsourced_Profiles",
  "Côte-d'Or": "Côte-d'Or,_Unsourced_Profiles",
  "Côtes-d'Armor": "Côtes-d'Armor,_Unsourced_Profiles",
  "Danby Wiske": "Danby_Wiske,_Yorkshire,_Unsourced_Profiles",
  "Davis Name Study": "Davis_Name_Study,_Unsourced_Profiles",
  Delaware: "Delaware,_Unsourced_Profiles",
  Denbighshire: "Denbighshire,_Unsourced_Profiles",
  Denmark: "Denmark,_Unsourced_Profiles",
  Derbyshire: "Derbyshire,_Unsourced_Profiles",
  "Deux-Sèvres": "Deux-Sèvres,_Unsourced_Profiles",
  Devon: "Devon,_Unsourced_Profiles",
  "District of Columbia": "District_of_Columbia,_Unsourced_Profiles",
  Dominica: "Dominica,_Unsourced_Profiles",
  Dordogne: "Dordogne,_Unsourced_Profiles",
  Dorset: "Dorset,_Unsourced_Profiles",
  Doubs: "Doubs,_Unsourced_Profiles",
  Drôme: "Drôme,_Unsourced_Profiles",
  "Dubreuil Name Study": "Dubreuil_Name_Study,_Unsourced_Profiles",
  Dumfriesshire: "Dumfriesshire,_Unsourced_Profiles",
  Dunbartonshire: "Dunbartonshire,_Unsourced_Profiles",
  Durango: "Durango,_Unsourced_Profiles",
  Durham: "Durham,_Unsourced_Profiles",
  "Dwight Name Study": "Dwight_Name_Study,_Unsourced",
  "Dyess Name Study": "Dyess_Name_Study,_Unsourced_Profiles",
  "Early Scandinavia": "Early_Scandinavia,_Unsourced_Profiles",
  "East Lothian": "East_Lothian,_Unsourced_Profiles",
  Ecuador: "Ecuador,_Unsourced_Profiles",
  Edinburgh: "Edinburgh,_Unsourced_Profiles",
  Egypt: "Egypt,_Unsourced_Profiles",
  "Ellis Name Study": "Ellis_Name_Study,_Unsourced_Profiles",
  England: "England,_Unsourced_Profiles",
  "Ennis Name Study": "Ennis_Name_Study,_Unsourced_Profiles",
  Essex: "Essex,_Unsourced_Profiles",
  Essonne: "Essonne,_Unsourced_Profiles",
  Estonia: "Estonia,_Unsourced_Profiles",
  Eure: "Eure,_Unsourced_Profiles",
  "Eure-et-Loir": "Eure-et-Loir,_Unsourced_Profiles",
  Europe: "Europe,_Unsourced_Profiles",
  "Falkland Islands": "Falkland_Islands,_Unsourced_Profiles",
  Fife: "Fife,_Unsourced_Profiles",
  Fiji: "Fiji,_Unsourced_Profiles",
  "Filles du Roi": "Filles_du_Roi,_Unsourced_Profiles",
  Finistère: "Finistère,_Unsourced_Profiles",
  Finland: "Finland,_Unsourced_Profiles",
  Flanders: "Flanders,_Unsourced_Profiles",
  Flintshire: "Flintshire,_Unsourced_Profiles",
  Florida: "Florida,_Unsourced_Profiles",
  Forfarshire: "Forfarshire,_Unsourced_Profiles",
  "Forster Name Study": "Forster_Name_Study,_Unsourced_Profiles",
  "Free State Province": "Free_State_Province,_Unsourced_Profiles",
  "French Guiana": "French_Guiana,_Unsourced_Profiles",
  Gard: "Gard,_Unsourced_Profiles",
  "Gardner Name Study": "Gardner_Name_Study,_Unsourced_Profiles",
  Georgia: "Georgia,_Unsourced_Profiles",
  Gers: "Gers,_Unsourced_Profiles",
  Ghana: "Ghana,_Unsourced_Profiles",
  Gironde: "Gironde,_Unsourced_Profiles",
  Glamorgan: "Glamorgan,_Unsourced_Profiles",
  Glasgow: "Glasgow,_Unsourced_Profiles",
  Gloucestershire: "Gloucestershire,_Unsourced_Profiles",
  "Gordon Name Study": "Gordon_Name_Study,_Unsourced_Profiles",
  "Gray Name Study": "Gray_Name_Study,_Unsourced_Profiles",
  "Greater Manchester": "Greater_Manchester,_Unsourced_Profiles",
  Greece: "Greece,_Unsourced_Profiles",
  "Greer Name Study": "Greer_Name_Study,_Unsourced_Profiles",
  Grenada: "Grenada,_Unsourced_Profiles",
  Guadeloupe: "Guadeloupe,_Unsourced_Profiles",
  Guernsey: "Guernsey,_Unsourced_Profiles",
  Guyana: "Guyana,_Unsourced_Profiles",
  Hainaut: "Hainaut,_Unsourced_Profiles",
  Haiti: "Haiti,_Unsourced_Profiles",
  Hampshire: "Hampshire,_Unsourced_Profiles",
  "Harare Province": "Harare_Province,_Unsourced_Profiles",
  "Haut-Rhin": "Haut-Rhin,_Unsourced_Profiles",
  "Haute-Corse": "Haute-Corse,_Unsourced_Profiles",
  "Haute-Garonne": "Haute-Garonne,_Unsourced_Profiles",
  "Haute-Loire": "Haute-Loire,_Unsourced_Profiles",
  "Haute-Marne": "Haute-Marne,_Unsourced_Profiles",
  "Haute-Savoie": "Haute-Savoie,_Unsourced_Profiles",
  "Haute-Saône": "Haute-Saône,_Unsourced_Profiles",
  "Haute-Vienne": "Haute-Vienne,_Unsourced_Profiles",
  "Hautes-Alpes": "Hautes-Alpes,_Unsourced_Profiles",
  "Hautes-Pyrénées": "Hautes-Pyrénées,_Unsourced_Profiles",
  "Hauts-de-Seine": "Hauts-de-Seine,_Unsourced_Profiles",
  Hawaii: "Hawaii,_Unsourced_Profiles",
  "Hawkesford Name Study": "Hawkesford_Name_Study,_Unsourced_Profiles",
  Herefordshire: "Herefordshire,_Unsourced_Profiles",
  Hertfordshire: "Hertfordshire,_Unsourced_Profiles",
  Hesse: "Hesse,_Unsourced_Profiles",
  Holland: "Holland,_Unsourced_Profiles",
  Honduras: "Honduras,_Unsourced_Profiles",
  "Hudson Name Study": "Hudson_Name_Study,_Unsourced_Profiles",
  Huguenot: "Huguenot,_Unsourced_Profiles",
  Hungary: "Hungary,_Unsourced_Profiles",
  Huntingdonshire: "Huntingdonshire,_Unsourced_Profiles",
  "Hyser Name Study": "Hyser_Name_Study,_Unsourced_Profiles",
  Hérault: "Hérault,_Unsourced_Profiles",
  Iceland: "Iceland,_Unsourced_Profiles",
  Idaho: "Idaho,_Unsourced_Profiles",
  "Ille-et-Vilaine": "Ille-et-Vilaine,_Unsourced_Profiles",
  Illinois: "Illinois,_Unsourced_Profiles",
  India: "India,_Unsourced_Profiles",
  Indiana: "Indiana,_Unsourced_Profiles",
  Indonesia: "Indonesia,_Unsourced_Profiles",
  Indre: "Indre,_Unsourced_Profiles",
  "Indre-et-Loire": "Indre-et-Loire,_Unsourced_Profiles",
  "Inverness-shire": "Inverness-shire,_Unsourced_Profiles",
  Iowa: "Iowa,_Unsourced_Profiles",
  Iran: "Iran,_Unsourced_Profiles",
  Iraq: "Iraq,_Unsourced_Profiles",
  "Isle of Man": "Isle_of_Man,_Unsourced_Profiles",
  "Isle of Wight": "Isle_of_Wight,_Unsourced_Profiles",
  Israel: "Israel,_Unsourced_Profiles",
  Isère: "Isère,_Unsourced_Profiles",
  Italy: "Italy,_Unsourced_Profiles",
  Jalisco: "Jalisco,_Unsourced_Profiles",
  Jamaica: "Jamaica,_Unsourced_Profiles",
  Japan: "Japan,_Unsourced_Profiles",
  Jersey: "Jersey,_Unsourced_Profiles",
  Jordan: "Jordan,_Unsourced_Profiles",
  Jura: "Jura,_Unsourced_Profiles",
  Kansas: "Kansas,_Unsourced_Profiles",
  "Keil Name Study": "Keil_Name_Study,_Unsourced_Profiles",
  Kent: "Kent,_Unsourced_Profiles",
  Kentucky: "Kentucky,_Unsourced_Profiles",
  Kenya: "Kenya,_Unsourced_Profiles",
  Kincardineshire: "Kincardineshire,_Unsourced_Profiles",
  "Kinross-shire": "Kinross-shire,_Unsourced_Profiles",
  Kirkcudbrightshire: "Kirkcudbrightshire,_Unsourced_Profiles",
  Korea: "Korea,_Unsourced_Profiles",
  "KwaZulu Natal Province": "KwaZulu_Natal_Province,_Unsourced_Profiles",
  "Lail Name Study": "Lail_Name_Study,_Unsourced_Profiles",
  Lanarkshire: "Lanarkshire,_Unsourced_Profiles",
  Lancashire: "Lancashire,_Unsourced_Profiles",
  Landes: "Landes,_Unsourced_Profiles",
  Latvia: "Latvia,_Unsourced_Profiles",
  Lebanon: "Lebanon,_Unsourced_Profiles",
  Leicestershire: "Leicestershire,_Unsourced_Profiles",
  Liberia: "Liberia,_Unsourced_Profiles",
  Limburg: "Limburg,_Belgium,_Unsourced_Profiles",
  Lincolnshire: "Lincolnshire,_Unsourced_Profiles",
  Lithuania: "Lithuania,_Unsourced_Profiles",
  "Lohnes Name Study": "Lohnes_Name_Study,_Unsourced_Profiles",
  "Loir-et-Cher": "Loir-et-Cher,_Unsourced_Profiles",
  Loire: "Loire,_Unsourced_Profiles",
  "Loire-Atlantique": "Loire-Atlantique,_Unsourced_Profiles",
  Loiret: "Loiret,_Unsourced_Profiles",
  London: "London,_Unsourced_Profiles",
  Lot: "Lot,_Unsourced_Profiles",
  "Lot-et-Garonne": "Lot-et-Garonne,_Unsourced_Profiles",
  Louisiana: "Louisiana,_Unsourced_Profiles",
  "Lower Saxony": "Lower_Saxony,_Unsourced_Profiles",
  Lozère: "Lozère,_Unsourced_Profiles",
  Luxembourg: "Luxembourg,_Unsourced_Profiles",
  Lyon: "Lyon,_Unsourced_Profiles",
  Maine: "Maine,_Unsourced_Profiles",
  "Maine-et-Loire": "Maine-et-Loire,_Unsourced_Profiles",
  Malaysia: "Malaysia,_Unsourced_Profiles",
  Malta: "Malta,_Unsourced_Profiles",
  Manche: "Manche,_Unsourced_Profiles",
  Manitoba: "Manitoba,_Unsourced_Profiles",
  Martinique: "Martinique,_Unsourced_Profiles",
  Maryland: "Maryland,_Unsourced_Profiles",
  Massachusetts: "Massachusetts,_Unsourced_Profiles",
  Mauritius: "Mauritius,_Unsourced_Profiles",
  Mayenne: "Mayenne,_Unsourced_Profiles",
  "Mayo Name Study": "Mayo_Name_Study,_Unsourced_Profiles",
  Mecklenburg: "Mecklenburg,_Unsourced_Profiles",
  "Mecklenburg-Schwerin": "Mecklenburg-Schwerin,_Unsourced_Profiles",
  Medieval: "Medieval,_Unsourced_Profiles",
  Merionethshire: "Merionethshire,_Unsourced_Profiles",
  Merseyside: "Merseyside,_Unsourced_Profiles",
  "Meurthe-et-Moselle": "Meurthe-et-Moselle,_Unsourced_Profiles",
  Meuse: "Meuse,_Unsourced_Profiles",
  Mexico: "Mexico,_Unsourced_Profiles",
  Michigan: "Michigan,_Unsourced_Profiles",
  Middlesex: "Middlesex,_Unsourced_Profiles",
  Midlothian: "Midlothian,_Unsourced_Profiles",
  Minnesota: "Minnesota,_Unsourced_Profiles",
  Mississippi: "Mississippi,_Unsourced_Profiles",
  Missouri: "Missouri,_Unsourced_Profiles",
  Mongolia: "Mongolia,_Unsourced_Profiles",
  Monmouthshire: "Monmouthshire,_Unsourced_Profiles",
  Montana: "Montana,_Unsourced_Profiles",
  Montgomeryshire: "Montgomeryshire,_Unsourced_Profiles",
  Moray: "Moray,_Unsourced_Profiles",
  Morbihan: "Morbihan,_Unsourced_Profiles",
  Morocco: "Morocco,_Unsourced_Profiles",
  Moselle: "Moselle,_Unsourced_Profiles",
  "Mullis Name Study": "Mullis_Name_Study,_Unsourced_Profiles",
  "Murray Name Study": "Murray_Name_Study,_Unsourced_Profiles",
  Myanmar: "Myanmar,_Unsourced_Profiles",
  Nairn: "Nairn,_Unsourced_Profiles",
  "Napier Name Study": "Napier_Name_Study,_Unsourced_Profiles",
  "Natal Province": "Natal_Province,_Unsourced_Profiles",
  "Native American": "Native_American,_Unsourced_Profiles",
  "Native Americans": "Native_Americans,_Unsourced_Profiles",
  Nebraska: "Nebraska,_Unsourced_Profiles",
  Nepal: "Nepal,_Unsourced_Profiles",
  Netherlands: "Netherlands,_Unsourced_Profiles",
  Nevada: "Nevada,_Unsourced_Profiles",
  "New Brunswick": "New_Brunswick,_Unsourced_Profiles",
  "New Hampshire": "New_Hampshire,_Unsourced_Profiles",
  "New Jersey": "New_Jersey,_Unsourced_Profiles",
  "New Mexico": "New_Mexico,_Unsourced_Profiles",
  "New Netherland": "New_Netherland,_Unsourced_Profiles",
  "New South Wales": "New_South_Wales,_Unsourced_Profiles",
  "New Sweden": "New_Sweden,_Unsourced_Profiles",
  "New York": "New_York,_Unsourced_Profiles",
  Newfoundland: "Newfoundland,_Unsourced_Profiles",
  Nicaragua: "Nicaragua,_Unsourced_Profiles",
  Nièvre: "Nièvre,_Unsourced_Profiles",
  Nord: "Nord,_Unsourced_Profiles",
  "Nordrhein-Westfalen": "Nordrhein-Westfalen,_Unsourced_Profiles",
  Norfolk: "Norfolk,_Unsourced_Profiles",
  "North America": "North_America,_Unsourced_Profiles",
  "North Carolina": "North_Carolina,_Unsourced_Profiles",
  "North Dakota": "North_Dakota,_Unsourced_Profiles",
  "North Rhine-Westphalia": "North_Rhine-Westphalia,_Unsourced_Profiles",
  Northamptonshire: "Northamptonshire,_Unsourced_Profiles",
  "Northern Rhodesia": "Northern_Rhodesia,_Unsourced_Profiles",
  "Northern Territory": "Northern_Territory,_Unsourced_Profiles",
  Northumberland: "Northumberland,_Unsourced_Profiles",
  Norway: "Norway,_Unsourced_Profiles",
  Nottinghamshire: "Nottinghamshire,_Unsourced_Profiles",
  "Nova Scotia": "Nova_Scotia,_Unsourced_Profiles",
  Nunavut: "Nunavut,_Unsourced_Profiles",
  Oceania: "Oceania,_Unsourced_Profiles",
  "Ogle Name Study": "Ogle_Name_Study,_Unsourced_Profiles",
  Ohio: "Ohio,_Unsourced_Profiles",
  Oise: "Oise,_Unsourced_Profiles",
  Oklahoma: "Oklahoma,_Unsourced_Profiles",
  Ontario: "Ontario,_Unsourced_Profiles",
  "Oost-Vlaanderen": "Oost-Vlaanderen,_Unsourced_Profiles",
  Oregon: "Oregon,_Unsourced_Profiles",
  Orkney: "Orkney,_Unsourced_Profiles",
  Orne: "Orne,_Unsourced_Profiles",
  "Overbey Name Study": "Overbey_Name_Study,_Unsourced_Profiles",
  Oxfordshire: "Oxfordshire,_Unsourced_Profiles",
  "Pacific Nations": "Pacific_Nations,_Unsourced_Profiles",
  Pakistan: "Pakistan,_Unsourced_Profiles",
  Palestine: "Palestine,_Unsourced_Profiles",
  Panama: "Panama,_Unsourced_Profiles",
  Paris: "Paris,_Unsourced_Profiles",
  "Pas-de-Calais": "Pas-de-Calais,_Unsourced_Profiles",
  Peeblesshire: "Peeblesshire,_Unsourced_Profiles",
  Pembrokeshire: "Pembrokeshire,_Unsourced_Profiles",
  Pennsylvania: "Pennsylvania,_Unsourced_Profiles",
  Perthshire: "Perthshire,_Unsourced_Profiles",
  Peru: "Peru,_Unsourced_Profiles",
  Philippines: "Philippines,_Unsourced_Profiles",
  "Pike Name Study": "Pike_Name_Study,_Unsourced_Profiles",
  "Pillichody Name Study": "Pillichody_Name_Study,_Unsourced_Profiles",
  "Plaisted Name Study": "Plaisted_Name_Study,_Unsourced_Profiles",
  Pocahontas: "Pocahontas,_Unsourced_Profiles",
  Poland: "Poland,_Unsourced_Profiles",
  Polynesia: "Polynesia,_Unsourced_Profiles",
  Portugal: "Portugal,_Unsourced_Profiles",
  "Portuguese East Africa": "Portuguese_East_Africa,_Unsourced_Profiles",
  "Prince Edward Island": "Prince_Edward_Island,_Unsourced_Profiles",
  Project: "Project,_Unsourced_Profiles",
  "Propst Name Study": "Propst_Name_Study,_Unsourced_Profiles",
  "Province de Liège": "Province_de_Liège,_Unsourced_Profiles",
  "Province de Namur": "Province_de_Namur,_Unsourced_Profiles",
  "Province of Antwerp": "Province_of_Antwerp,_Unsourced_Profiles",
  Prussia: "Prussia,_Unsourced_Profiles",
  "Puerto Rico": "Puerto_Rico,_Unsourced_Profiles",
  "Puritan Great Migration": "Puritan_Great_Migration,_Unsourced_Profiles",
  "Puy-de-Dôme": "Puy-de-Dôme,_Unsourced_Profiles",
  "Pyrénées-Atlantiques": "Pyrénées-Atlantiques,_Unsourced_Profiles",
  "Pyrénées-Orientales": "Pyrénées-Orientales,_Unsourced_Profiles",
  Quakers: "Quakers,_Unsourced_Profiles",
  Quebec: "Quebec,_Unsourced_Profiles",
  Queensland: "Queensland,_Unsourced_Profiles",
  Québec: "Québec,_Unsourced_Profiles",
  Radnorshire: "Radnorshire,_Unsourced_Profiles",
  Rajasthan: "Rajasthan,_Unsourced_Profiles",
  Raton: "Raton,_New_Mexico_One_Place_Study,_Unsourced",
  "Ream Name Study": "Ream_Name_Study,_Unsourced_Profiles",
  Renfrewshire: "Renfrewshire,_Unsourced_Profiles",
  "Rheinland-Pfalz": "Rheinland-Pfalz,_Unsourced_Profiles",
  "Rhineland-Palatinate": "Rhineland-Palatinate,_Unsourced_Profiles",
  "Rhode Island": "Rhode_Island,_Unsourced_Profiles",
  Rhodesia: "Rhodesia,_Unsourced_Profiles",
  Rhône: "Rhône,_Unsourced_Profiles",
  Romania: "Romania,_Unsourced_Profiles",
  "Ross and Cromarty": "Ross_and_Cromarty,_Unsourced_Profiles",
  Roxburghshire: "Roxburghshire,_Unsourced_Profiles",
  Russia: "Russia,_Unsourced_Profiles",
  "Russian Empire": "Russian_Empire,_Unsourced_Profiles",
  Rutland: "Rutland,_Unsourced_Profiles",
  Saarland: "Saarland,_Unsourced_Profiles",
  Sachsen: "Sachsen,_Unsourced_Profiles",
  "Saint Kitts and Nevis": "Saint_Kitts_and_Nevis,_Unsourced_Profiles",
  "Saint Thomas": "Saint_Thomas,_Danish_West_Indies,_Unsourced_Profiles",
  "Saint-Barthélemy": "Saint-Barthélemy,_Unsourced_Profiles",
  Samoa: "Samoa,_Unsourced_Profiles",
  Sarthe: "Sarthe,_Unsourced_Profiles",
  Saskatchewan: "Saskatchewan,_Unsourced_Profiles",
  Savoie: "Savoie,_Unsourced_Profiles",
  Saxony: "Saxony,_Unsourced_Profiles",
  "Saône-et-Loire": "Saône-et-Loire,_Unsourced_Profiles",
  "Schindler Name Study": "Schindler_Name_Study,_Unsourced_Profiles",
  "Schleswig-Holstein": "Schleswig-Holstein,_Unsourced_Profiles",
  "Seine-Maritime": "Seine-Maritime,_Unsourced_Profiles",
  "Seine-Saint-Denis": "Seine-Saint-Denis,_Unsourced_Profiles",
  "Seine-et-Marne": "Seine-et-Marne,_Unsourced_Profiles",
  Selkirkshire: "Selkirkshire,_Unsourced_Profiles",
  "Selvaggio Name Study": "Selvaggio_Name_Study,_Unsourced_Profiles",
  Serbia: "Serbia,_Unsourced_Profiles",
  Seychelles: "Seychelles,_Unsourced_Profiles",
  Shetland: "Shetland,_Unsourced_Profiles",
  "Shockey Name Study": "Shockey_Name_Study,_Unsourced_Profiles",
  "Shotwell Name Study": "Shotwell_Name_Study,_Unsourced_Profiles",
  Shropshire: "Shropshire,_Unsourced_Profiles",
  Sicily: "Sicily,_Unsourced_Profiles",
  Singapore: "Singapore,_Unsourced_Profiles",
  "Sint Eustatius": "Sint_Eustatius,_Unsourced_Profiles",
  Slovakia: "Slovakia,_Unsourced_Profiles",
  Slovenia: "Slovenia,_Unsourced_Profiles",
  Somerset: "Somerset,_Unsourced_Profiles",
  Somme: "Somme,_Unsourced_Profiles",
  "South Africa": "South_Africa,_Unsourced_Profiles",
  "South America": "South_America,_Unsourced_Profiles",
  "South Australia": "South_Australia,_Unsourced_Profiles",
  "South Carolina": "South_Carolina,_Unsourced_Profiles",
  "South Dakota": "South_Dakota,_Unsourced_Profiles",
  "South Korea": "South_Korea,_Unsourced_Profiles",
  "Southern Pioneers": "Southern_Pioneers,_Unsourced_Profiles",
  "Southern Rhodesia": "Southern_Rhodesia,_Unsourced_Profiles",
  "Spann Name Study": "Spann_Name_Study,_Unsourced_Profiles",
  "Sperry Name Study": "Sperry_Name_Study,_Unsourced_Profiles",
  "Sri Lanka": "Sri_Lanka,_Unsourced_Profiles",
  "St. Vincent": "St._Vincent,_Unsourced_Profiles",
  Staffordshire: "Staffordshire,_Unsourced_Profiles",
  "Stermenszky Name Study": "Stermenszky_Name_Study,_Unsourced_Profiles",
  Stirlingshire: "Stirlingshire,_Unsourced_Profiles",
  "Stobo Name Study": "Stobo_Name_Study,_Unsourced_Profiles",
  "Stone Name Study": "Stone_Name_Study,_Unsourced_Profiles",
  "Stover Name Study": "Stover_Name_Study,_Unsourced_Profiles",
  Strathclyde: "Strathclyde,_Unsourced_Profiles",
  Suffolk: "Suffolk,_Unsourced_Profiles",
  Suriname: "Suriname,_Unsourced_Profiles",
  Surrey: "Surrey,_Unsourced_Profiles",
  Sussex: "Sussex,_Unsourced_Profiles",
  Sutherland: "Sutherland,_Unsourced_Profiles",
  Sweden: "Sweden,_Unsourced_Profiles",
  "Swedish Estonia": "Swedish_Estonia,_Unsourced_Profiles",
  Switzerland: "Switzerland,_Unsourced_Profiles",
  Syria: "Syria,_Unsourced_Profiles",
  Taiwan: "Taiwan,_Unsourced_Profiles",
  Tanzania: "Tanzania,_Unsourced_Profiles",
  Tarn: "Tarn,_Unsourced_Profiles",
  "Tarn-et-Garonne": "Tarn-et-Garonne,_Unsourced_Profiles",
  Tasmania: "Tasmania,_Unsourced_Profiles",
  Tennessee: "Tennessee,_Unsourced_Profiles",
  "Territoire de Belfort": "Territoire_de_Belfort,_Unsourced_Profiles",
  Texas: "Texas,_Unsourced_Profiles",
  Thailand: "Thailand,_Unsourced_Profiles",
  "The Bahamas": "The_Bahamas,_Unsourced_Profiles",
  "Thurber Name Study": "Thurber_Name_Study,_Unsourced_Profiles",
  Thuringia: "Thuringia,_Unsourced_Profiles",
  Thüringen: "Thüringen,_Unsourced_Profiles",
  Tonga: "Tonga,_Unsourced_Profiles",
  "Transvaal Province": "Transvaal_Province,_Unsourced_Profiles",
  "Trinidad and Tobago": "Trinidad_and_Tobago,_Unsourced_Profiles",
  Trinidad: "Trinidad,_Unsourced_Profiles",
  Tunisia: "Tunisia,_Unsourced_Profiles",
  Turkey: "Turkey,_Unsourced_Profiles",
  "US Virgin Islands": "US_Virgin_Islands,_Unsourced_Profiles",
  Ukraine: "Ukraine,_Unsourced_Profiles",
  "United States": "United_States,_Unsourced_Profiles",
  Uruguay: "Uruguay,_Unsourced_Profiles",
  Utah: "Utah,_Unsourced_Profiles",
  "Val-d'Oise": "Val-d'Oise,_Unsourced_Profiles",
  "Val-de-Marne": "Val-de-Marne,_Unsourced_Profiles",
  Var: "Var,_Unsourced_Profiles",
  Vaucluse: "Vaucluse,_Unsourced_Profiles",
  Vendée: "Vendée,_Unsourced_Profiles",
  Venezuela: "Venezuela,_Unsourced_Profiles",
  Vermont: "Vermont,_Unsourced_Profiles",
  Victoria: "Victoria,_Unsourced_Profiles",
  Vienne: "Vienne,_Unsourced_Profiles",
  Vietnam: "Vietnam,_Unsourced_Profiles",
  Virginia: "Virginia,_Unsourced_Profiles",
  "Vlaams-Brabant": "Vlaams-Brabant,_Unsourced_Profiles",
  "Volga Germans": "Volga_Germans,_Unsourced_Profiles",
  Vosges: "Vosges,_Unsourced_Profiles",
  Wales: "Wales,_Unsourced_Profiles",
  Warwickshire: "Warwickshire,_Unsourced_Profiles",
  Washington: "Washington,_Unsourced_Profiles",
  Wessex: "Wessex,_Unsourced_Profiles",
  "West Indies": "West_Indies,_Unsourced_Profiles",
  "West Lothian": "West_Lothian,_Unsourced_Profiles",
  "West Virginia": "West_Virginia,_Unsourced_Profiles",
  "West-Vlaanderen": "West-Vlaanderen,_Unsourced_Profiles",
  "Western Australia": "Western_Australia,_Unsourced_Profiles",
  Westmorland: "Westmorland,_Unsourced_Profiles",
  Wigtownshire: "Wigtownshire,_Unsourced_Profiles",
  Wiltshire: "Wiltshire,_Unsourced_Profiles",
  Wisconsin: "Wisconsin,_Unsourced_Profiles",
  Worcestershire: "Worcestershire,_Unsourced_Profiles",
  Wyoming: "Wyoming,_Unsourced_Profiles",
  Württemberg: "Württemberg,_Unsourced_Profiles",
  Yonne: "Yonne,_Unsourced_Profiles",
  Yorkshire: "Yorkshire,_Unsourced_Profiles",
  Yugoslavia: "Yugoslavia,_Unsourced_Profiles",
  Yukon: "Yukon,_Unsourced_Profiles",
  Yvelines: "Yvelines,_Unsourced_Profiles",
  Zacatecas: "Zacatecas,_Unsourced_Profiles",
  Zimbabwe: "Zimbabwe,_Unsourced_Profiles",
  ÁEand: "ÁEand,_Unsourced_Profiles",
  Åland: "Åland,_Unsourced_Profiles",
};
